# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PhaseLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhaseLabel.sizePolicy().hasHeightForWidth())
        self.PhaseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.PhaseLabel.setFont(font)
        self.PhaseLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.PhaseLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PhaseLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PhaseLabel.setObjectName("PhaseLabel")
        self.gridLayout_2.addWidget(self.PhaseLabel, 0, 0, 1, 8)
        self.WeightLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WeightLabel.sizePolicy().hasHeightForWidth())
        self.WeightLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.WeightLabel.setFont(font)
        self.WeightLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.WeightLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WeightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WeightLabel.setObjectName("WeightLabel")
        self.gridLayout_2.addWidget(self.WeightLabel, 0, 8, 2, 1)
        self.LevLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevLabel.sizePolicy().hasHeightForWidth())
        self.LevLabel.setSizePolicy(sizePolicy)
        self.LevLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LevLabel.setObjectName("LevLabel")
        self.gridLayout_2.addWidget(self.LevLabel, 1, 0, 1, 1)
        self.LevRadioButton0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton0.sizePolicy().hasHeightForWidth())
        self.LevRadioButton0.setSizePolicy(sizePolicy)
        self.LevRadioButton0.setText("")
        self.LevRadioButton0.setCheckable(True)
        self.LevRadioButton0.setAutoExclusive(False)
        self.LevRadioButton0.setObjectName("LevRadioButton0")
        self.gridLayout_2.addWidget(self.LevRadioButton0, 1, 1, 1, 1)
        self.LevRadioButton1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton1.sizePolicy().hasHeightForWidth())
        self.LevRadioButton1.setSizePolicy(sizePolicy)
        self.LevRadioButton1.setText("")
        self.LevRadioButton1.setCheckable(True)
        self.LevRadioButton1.setAutoExclusive(False)
        self.LevRadioButton1.setObjectName("LevRadioButton1")
        self.gridLayout_2.addWidget(self.LevRadioButton1, 1, 2, 1, 1)
        self.LevRadioButton2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton2.sizePolicy().hasHeightForWidth())
        self.LevRadioButton2.setSizePolicy(sizePolicy)
        self.LevRadioButton2.setText("")
        self.LevRadioButton2.setCheckable(True)
        self.LevRadioButton2.setAutoExclusive(False)
        self.LevRadioButton2.setObjectName("LevRadioButton2")
        self.gridLayout_2.addWidget(self.LevRadioButton2, 1, 3, 1, 1)
        self.OverRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OverRadioButton.sizePolicy().hasHeightForWidth())
        self.OverRadioButton.setSizePolicy(sizePolicy)
        self.OverRadioButton.setText("")
        self.OverRadioButton.setCheckable(True)
        self.OverRadioButton.setAutoExclusive(False)
        self.OverRadioButton.setObjectName("OverRadioButton")
        self.gridLayout_2.addWidget(self.OverRadioButton, 1, 4, 1, 1)
        self.TareRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TareRadioButton.sizePolicy().hasHeightForWidth())
        self.TareRadioButton.setSizePolicy(sizePolicy)
        self.TareRadioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TareRadioButton.setAutoFillBackground(True)
        self.TareRadioButton.setObjectName("TareRadioButton")
        self.gridLayout_2.addWidget(self.TareRadioButton, 1, 5, 1, 1)
        self.StabLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StabLabel.sizePolicy().hasHeightForWidth())
        self.StabLabel.setSizePolicy(sizePolicy)
        self.StabLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StabLabel.setObjectName("StabLabel")
        self.gridLayout_2.addWidget(self.StabLabel, 1, 6, 1, 1)
        self.StabRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StabRadioButton.sizePolicy().hasHeightForWidth())
        self.StabRadioButton.setSizePolicy(sizePolicy)
        self.StabRadioButton.setText("")
        self.StabRadioButton.setCheckable(True)
        self.StabRadioButton.setAutoExclusive(False)
        self.StabRadioButton.setObjectName("StabRadioButton")
        self.gridLayout_2.addWidget(self.StabRadioButton, 1, 7, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ParsPage = QtWidgets.QWidget()
        self.ParsPage.setObjectName("ParsPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ParsPage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.ParsPage)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        self.ParNameLabel = QtWidgets.QLabel(self.ParsPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ParNameLabel.setFont(font)
        self.ParNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ParNameLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ParNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ParNameLabel.setObjectName("ParNameLabel")
        self.gridLayout_5.addWidget(self.ParNameLabel, 1, 0, 1, 1)
        self.ParsWidget = QtWidgets.QWidget(self.ParsPage)
        self.ParsWidget.setObjectName("ParsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ParsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ParNPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParNPushButton.setFont(font)
        self.ParNPushButton.setObjectName("ParNPushButton")
        self.horizontalLayout.addWidget(self.ParNPushButton)
        self.NextPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NextPushButton.setFont(font)
        self.NextPushButton.setObjectName("NextPushButton")
        self.horizontalLayout.addWidget(self.NextPushButton)
        self.PrevPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PrevPushButton.setFont(font)
        self.PrevPushButton.setObjectName("PrevPushButton")
        self.horizontalLayout.addWidget(self.PrevPushButton)
        self.ParVPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParVPushButton.setFont(font)
        self.ParVPushButton.setObjectName("ParVPushButton")
        self.horizontalLayout.addWidget(self.ParVPushButton)
        self.gridLayout_5.addWidget(self.ParsWidget, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.ParsPage)
        self.DosePage = QtWidgets.QWidget()
        self.DosePage.setObjectName("DosePage")
        self.gridLayout = QtWidgets.QGridLayout(self.DosePage)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.DosePage)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem2 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 3)
        self.DoseLabel = QtWidgets.QLabel(self.DosePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoseLabel.sizePolicy().hasHeightForWidth())
        self.DoseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.DoseLabel.setFont(font)
        self.DoseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DoseLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DoseLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DoseLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DoseLabel.setObjectName("DoseLabel")
        self.gridLayout.addWidget(self.DoseLabel, 2, 0, 1, 1)
        self.TotalLabel = QtWidgets.QLabel(self.DosePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalLabel.sizePolicy().hasHeightForWidth())
        self.TotalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalLabel.setObjectName("TotalLabel")
        self.gridLayout.addWidget(self.TotalLabel, 3, 0, 1, 1)
        self.DoseNomPushButton = QtWidgets.QPushButton(self.DosePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DoseNomPushButton.setFont(font)
        self.DoseNomPushButton.setObjectName("DoseNomPushButton")
        self.gridLayout.addWidget(self.DoseNomPushButton, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.DosePage)
        self.ClbrPage = QtWidgets.QWidget()
        self.ClbrPage.setObjectName("ClbrPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ClbrPage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(78, 26, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 5, 1, 1)
        self.ClbPushButton0 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton0.sizePolicy().hasHeightForWidth())
        self.ClbPushButton0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton0.setFont(font)
        self.ClbPushButton0.setObjectName("ClbPushButton0")
        self.gridLayout_3.addWidget(self.ClbPushButton0, 1, 0, 1, 1)
        self.ClbLabel1 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel1.setFont(font)
        self.ClbLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel1.setObjectName("ClbLabel1")
        self.gridLayout_3.addWidget(self.ClbLabel1, 1, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 3, 1, 1)
        self.ClbPushButton1 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton1.sizePolicy().hasHeightForWidth())
        self.ClbPushButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton1.setFont(font)
        self.ClbPushButton1.setObjectName("ClbPushButton1")
        self.gridLayout_3.addWidget(self.ClbPushButton1, 1, 4, 1, 1)
        self.ClbLabel0 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel0.setFont(font)
        self.ClbLabel0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel0.setObjectName("ClbLabel0")
        self.gridLayout_3.addWidget(self.ClbLabel0, 1, 5, 1, 1)
        self.ClbPushButton2 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton2.sizePolicy().hasHeightForWidth())
        self.ClbPushButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton2.setFont(font)
        self.ClbPushButton2.setObjectName("ClbPushButton2")
        self.gridLayout_3.addWidget(self.ClbPushButton2, 2, 0, 1, 1)
        self.ClbLabel3 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel3.setFont(font)
        self.ClbLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel3.setObjectName("ClbLabel3")
        self.gridLayout_3.addWidget(self.ClbLabel3, 2, 1, 1, 2)
        self.ClbPushButton3 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton3.sizePolicy().hasHeightForWidth())
        self.ClbPushButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton3.setFont(font)
        self.ClbPushButton3.setObjectName("ClbPushButton3")
        self.gridLayout_3.addWidget(self.ClbPushButton3, 2, 4, 1, 1)
        self.ClbLabel2 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel2.setFont(font)
        self.ClbLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel2.setObjectName("ClbLabel2")
        self.gridLayout_3.addWidget(self.ClbLabel2, 2, 5, 1, 1)
        self.AdcLabel = QtWidgets.QLabel(self.ClbrPage)
        self.AdcLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AdcLabel.setObjectName("AdcLabel")
        self.gridLayout_3.addWidget(self.AdcLabel, 3, 0, 1, 1)
        self.AdcCodeLabel = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.AdcCodeLabel.setFont(font)
        self.AdcCodeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdcCodeLabel.setObjectName("AdcCodeLabel")
        self.gridLayout_3.addWidget(self.AdcCodeLabel, 3, 1, 1, 2)
        self.ZeroPushButton = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZeroPushButton.sizePolicy().hasHeightForWidth())
        self.ZeroPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ZeroPushButton.setFont(font)
        self.ZeroPushButton.setObjectName("ZeroPushButton")
        self.gridLayout_3.addWidget(self.ZeroPushButton, 3, 4, 1, 1)
        self.ZeroLabel = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ZeroLabel.setFont(font)
        self.ZeroLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZeroLabel.setObjectName("ZeroLabel")
        self.gridLayout_3.addWidget(self.ZeroLabel, 3, 5, 1, 1)
        self.stackedWidget.addWidget(self.ClbrPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.spinBox = QtWidgets.QSpinBox(self.page_2)
        self.spinBox.setGeometry(QtCore.QRect(120, 60, 50, 30))
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(240, 60, 72, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.dateEdit = QtWidgets.QDateEdit(self.page_2)
        self.dateEdit.setGeometry(QtCore.QRect(130, 100, 116, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_4.addWidget(self.pushButton_8, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 0, 1, 5)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 9)
        self.LevRadioButton0.raise_()
        self.PhaseLabel.raise_()
        self.StabRadioButton.raise_()
        self.StabLabel.raise_()
        self.LevLabel.raise_()
        self.WeightLabel.raise_()
        self.OverRadioButton.raise_()
        self.TareRadioButton.raise_()
        self.LevRadioButton2.raise_()
        self.LevRadioButton1.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 475, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuCLBR = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCLBR.setFont(font)
        self.menuCLBR.setObjectName("menuCLBR")
        self.menuRep = QtWidgets.QMenu(self.menuCLBR)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuRep.setFont(font)
        self.menuRep.setObjectName("menuRep")
        self.menuClb = QtWidgets.QMenu(self.menuCLBR)
        self.menuClb.setObjectName("menuClb")
        self.menuCONF = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCONF.setFont(font)
        self.menuCONF.setObjectName("menuCONF")
        self.menuTIME = QtWidgets.QMenu(self.menuCONF)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuTIME.setFont(font)
        self.menuTIME.setObjectName("menuTIME")
        self.menuWEIGHT = QtWidgets.QMenu(self.menuCONF)
        self.menuWEIGHT.setObjectName("menuWEIGHT")
        self.menuNNN = QtWidgets.QMenu(self.menuCONF)
        self.menuNNN.setObjectName("menuNNN")
        self.menuFLAGS = QtWidgets.QMenu(self.menuCONF)
        self.menuFLAGS.setObjectName("menuFLAGS")
        self.menuOPER = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuOPER.setFont(font)
        self.menuOPER.setObjectName("menuOPER")
        self.menuPORT = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuPORT.setFont(font)
        self.menuPORT.setObjectName("menuPORT")
        self.menuQuit = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuQuit.setFont(font)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menuBar)
        self.PcsNAction = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.PcsNAction.setFont(font)
        self.PcsNAction.setObjectName("PcsNAction")
        self.RoundAction = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RoundAction.setFont(font)
        self.RoundAction.setObjectName("RoundAction")
        self.RepAction0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction0.setFont(font)
        self.RepAction0.setObjectName("RepAction0")
        self.RepAction1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction1.setFont(font)
        self.RepAction1.setObjectName("RepAction1")
        self.RepAction2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction2.setFont(font)
        self.RepAction2.setObjectName("RepAction2")
        self.RepAction3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction3.setFont(font)
        self.RepAction3.setObjectName("RepAction3")
        self.ClbAction0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction0.setFont(font)
        self.ClbAction0.setObjectName("ClbAction0")
        self.ClbAction1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction1.setFont(font)
        self.ClbAction1.setObjectName("ClbAction1")
        self.ClbAction2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction2.setFont(font)
        self.ClbAction2.setObjectName("ClbAction2")
        self.ClbAction3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction3.setFont(font)
        self.ClbAction3.setObjectName("ClbAction3")
        self.actionUnld = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUnld.setFont(font)
        self.actionUnld.setObjectName("actionUnld")
        self.actionPreFeed = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionPreFeed.setFont(font)
        self.actionPreFeed.setObjectName("actionPreFeed")
        self.actionPreMeas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionPreMeas.setFont(font)
        self.actionPreMeas.setObjectName("actionPreMeas")
        self.actionBtmChk = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionBtmChk.setFont(font)
        self.actionBtmChk.setObjectName("actionBtmChk")
        self.actionShrtTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionShrtTMO.setFont(font)
        self.actionShrtTMO.setObjectName("actionShrtTMO")
        self.actionLongTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionLongTMO.setFont(font)
        self.actionLongTMO.setObjectName("actionLongTMO")
        self.actionSleep = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSleep.setFont(font)
        self.actionSleep.setObjectName("actionSleep")
        self.actionReady = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionReady.setFont(font)
        self.actionReady.setObjectName("actionReady")
        self.actionCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionCycle.setFont(font)
        self.actionCycle.setObjectName("actionCycle")
        self.actionTSmin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTSmin.setFont(font)
        self.actionTSmin.setObjectName("actionTSmin")
        self.actionDoza = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDoza.setFont(font)
        self.actionDoza.setObjectName("actionDoza")
        self.actionUpr1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUpr1.setFont(font)
        self.actionUpr1.setObjectName("actionUpr1")
        self.actionUpr2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUpr2.setFont(font)
        self.actionUpr2.setObjectName("actionUpr2")
        self.actionDozZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDozZ.setFont(font)
        self.actionDozZ.setObjectName("actionDozZ")
        self.actionTarZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTarZ.setFont(font)
        self.actionTarZ.setObjectName("actionTarZ")
        self.actionDebounce = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDebounce.setFont(font)
        self.actionDebounce.setObjectName("actionDebounce")
        self.actionTareSkip = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTareSkip.setFont(font)
        self.actionTareSkip.setObjectName("actionTareSkip")
        self.actionAutoCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAutoCycle.setFont(font)
        self.actionAutoCycle.setObjectName("actionAutoCycle")
        self.actionAutoStart = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAutoStart.setFont(font)
        self.actionAutoStart.setObjectName("actionAutoStart")
        self.actionFilterNN = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionFilterNN.setFont(font)
        self.actionFilterNN.setObjectName("actionFilterNN")
        self.actionAdapt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAdapt.setFont(font)
        self.actionAdapt.setObjectName("actionAdapt")
        self.MasterAction = QtWidgets.QAction(MainWindow)
        self.MasterAction.setObjectName("MasterAction")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuRep.addAction(self.RepAction0)
        self.menuRep.addAction(self.RepAction1)
        self.menuRep.addAction(self.RepAction2)
        self.menuRep.addAction(self.RepAction3)
        self.menuClb.addAction(self.ClbAction0)
        self.menuClb.addAction(self.ClbAction1)
        self.menuClb.addAction(self.ClbAction2)
        self.menuClb.addAction(self.ClbAction3)
        self.menuCLBR.addAction(self.menuRep.menuAction())
        self.menuCLBR.addAction(self.menuClb.menuAction())
        self.menuCLBR.addAction(self.PcsNAction)
        self.menuCLBR.addAction(self.RoundAction)
        self.menuCLBR.addAction(self.MasterAction)
        self.menuTIME.addAction(self.actionUnld)
        self.menuTIME.addAction(self.actionPreFeed)
        self.menuTIME.addAction(self.actionPreMeas)
        self.menuTIME.addAction(self.actionBtmChk)
        self.menuTIME.addAction(self.actionShrtTMO)
        self.menuTIME.addAction(self.actionLongTMO)
        self.menuTIME.addAction(self.actionSleep)
        self.menuTIME.addAction(self.actionReady)
        self.menuTIME.addAction(self.actionCycle)
        self.menuTIME.addAction(self.actionTSmin)
        self.menuWEIGHT.addAction(self.actionDoza)
        self.menuWEIGHT.addAction(self.actionUpr1)
        self.menuWEIGHT.addAction(self.actionUpr2)
        self.menuWEIGHT.addAction(self.actionDozZ)
        self.menuWEIGHT.addAction(self.actionTarZ)
        self.menuNNN.addAction(self.actionDebounce)
        self.menuNNN.addAction(self.actionTareSkip)
        self.menuNNN.addAction(self.actionFilterNN)
        self.menuNNN.addAction(self.actionAdapt)
        self.menuFLAGS.addAction(self.actionAutoCycle)
        self.menuFLAGS.addAction(self.actionAutoStart)
        self.menuCONF.addAction(self.menuTIME.menuAction())
        self.menuCONF.addAction(self.menuWEIGHT.menuAction())
        self.menuCONF.addAction(self.menuNNN.menuAction())
        self.menuCONF.addAction(self.menuFLAGS.menuAction())
        self.menuQuit.addAction(self.actionAbout)
        self.menuQuit.addAction(self.actionExit)
        self.menuBar.addAction(self.menuCLBR.menuAction())
        self.menuBar.addAction(self.menuCONF.menuAction())
        self.menuBar.addAction(self.menuOPER.menuAction())
        self.menuBar.addAction(self.menuPORT.menuAction())
        self.menuBar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PhaseLabel.setText(_translate("MainWindow", "00 : STOP_phase-bla-bla"))
        self.WeightLabel.setText(_translate("MainWindow", "-50.00kg"))
        self.LevLabel.setText(_translate("MainWindow", "LEVL"))
        self.TareRadioButton.setToolTip(_translate("MainWindow", "Fix tare"))
        self.TareRadioButton.setText(_translate("MainWindow", "TARE"))
        self.StabLabel.setText(_translate("MainWindow", "STAB"))
        self.pushButton.setText(_translate("MainWindow", "CLBR"))
        self.label_6.setText(_translate("MainWindow", "PARAMS"))
        self.pushButton_2.setText(_translate("MainWindow", "DOSE"))
        self.ParNameLabel.setText(_translate("MainWindow", "22: name of parameter:   -999999999 "))
        self.ParNPushButton.setText(_translate("MainWindow", "PAR N"))
        self.NextPushButton.setText(_translate("MainWindow", "NEXT"))
        self.PrevPushButton.setText(_translate("MainWindow", "PREV"))
        self.ParVPushButton.setText(_translate("MainWindow", "PAR V"))
        self.pushButton_4.setText(_translate("MainWindow", "PARS"))
        self.label_8.setText(_translate("MainWindow", "MAIN"))
        self.pushButton_3.setText(_translate("MainWindow", "LOGO"))
        self.DoseLabel.setText(_translate("MainWindow", "50.00kg"))
        self.TotalLabel.setText(_translate("MainWindow", "1234567.89kg"))
        self.DoseNomPushButton.setText(_translate("MainWindow", "Dose Nominal"))
        self.pushButton_6.setText(_translate("MainWindow", "LOGO"))
        self.label_7.setText(_translate("MainWindow", "CLBR"))
        self.pushButton_5.setText(_translate("MainWindow", "PARS"))
        self.ClbPushButton0.setText(_translate("MainWindow", "CLBR0"))
        self.ClbLabel1.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton1.setText(_translate("MainWindow", "CLBR1"))
        self.ClbLabel0.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton2.setText(_translate("MainWindow", "CLBR2"))
        self.ClbLabel3.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton3.setText(_translate("MainWindow", "CLBR3"))
        self.ClbLabel2.setText(_translate("MainWindow", "123456.789"))
        self.AdcLabel.setText(_translate("MainWindow", "ADC"))
        self.AdcCodeLabel.setText(_translate("MainWindow", "123456.789"))
        self.ZeroPushButton.setText(_translate("MainWindow", "ZERO"))
        self.ZeroLabel.setText(_translate("MainWindow", "-1234.56kg"))
        self.pushButton_8.setText(_translate("MainWindow", "CLBR"))
        self.label_5.setText(_translate("MainWindow", "LOGO"))
        self.pushButton_7.setText(_translate("MainWindow", "MAIN"))
        self.label.setText(_translate("MainWindow", "DVA TKM16 Batch Weigher Controler"))
        self.label_2.setText(_translate("MainWindow", "Program version 32"))
        self.label_3.setText(_translate("MainWindow", "Check sum 0xABCD"))
        self.label_4.setText(_translate("MainWindow", "TOKOM, Kyiv-2018                              tokom2009@gmail.com"))
        self.menuCLBR.setTitle(_translate("MainWindow", "CLBR"))
        self.menuRep.setTitle(_translate("MainWindow", "Rep"))
        self.menuClb.setTitle(_translate("MainWindow", "Clb"))
        self.menuCONF.setTitle(_translate("MainWindow", "CONF"))
        self.menuTIME.setTitle(_translate("MainWindow", "TIME"))
        self.menuWEIGHT.setTitle(_translate("MainWindow", "WEIGHT"))
        self.menuNNN.setTitle(_translate("MainWindow", "NNN"))
        self.menuFLAGS.setTitle(_translate("MainWindow", "FLAGS"))
        self.menuOPER.setTitle(_translate("MainWindow", "OPER"))
        self.menuPORT.setTitle(_translate("MainWindow", "PORT"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))
        self.PcsNAction.setText(_translate("MainWindow", "PcsN"))
        self.RoundAction.setText(_translate("MainWindow", "Round"))
        self.RepAction0.setText(_translate("MainWindow", "0"))
        self.RepAction1.setText(_translate("MainWindow", "1"))
        self.RepAction2.setText(_translate("MainWindow", "2"))
        self.RepAction3.setText(_translate("MainWindow", "3"))
        self.ClbAction0.setText(_translate("MainWindow", "0"))
        self.ClbAction1.setText(_translate("MainWindow", "1"))
        self.ClbAction2.setText(_translate("MainWindow", "2"))
        self.ClbAction3.setText(_translate("MainWindow", "3"))
        self.actionUnld.setText(_translate("MainWindow", "Unld"))
        self.actionPreFeed.setText(_translate("MainWindow", "PreFeed"))
        self.actionPreMeas.setText(_translate("MainWindow", "preMeas"))
        self.actionBtmChk.setText(_translate("MainWindow", "BtmChk"))
        self.actionShrtTMO.setText(_translate("MainWindow", "ShrtTMO"))
        self.actionLongTMO.setText(_translate("MainWindow", "LongTMO"))
        self.actionSleep.setText(_translate("MainWindow", "Sleep"))
        self.actionReady.setText(_translate("MainWindow", "Ready"))
        self.actionCycle.setText(_translate("MainWindow", "Cycle"))
        self.actionTSmin.setText(_translate("MainWindow", "TSmin"))
        self.actionDoza.setText(_translate("MainWindow", "Doza"))
        self.actionUpr1.setText(_translate("MainWindow", "Upr1"))
        self.actionUpr2.setText(_translate("MainWindow", "Upr2"))
        self.actionDozZ.setText(_translate("MainWindow", "DozZ"))
        self.actionTarZ.setText(_translate("MainWindow", "TarZ"))
        self.actionDebounce.setText(_translate("MainWindow", "Debounce"))
        self.actionTareSkip.setText(_translate("MainWindow", "TareSkip"))
        self.actionAutoCycle.setText(_translate("MainWindow", "AutoCycle"))
        self.actionAutoStart.setText(_translate("MainWindow", "AutoStart"))
        self.actionFilterNN.setText(_translate("MainWindow", "FilterNN"))
        self.actionAdapt.setText(_translate("MainWindow", "Adapt"))
        self.MasterAction.setText(_translate("MainWindow", "Master Bit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

