# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Phase_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.Phase_label.setFont(font)
        self.Phase_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Phase_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Phase_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Phase_label.setObjectName("Phase_label")
        self.gridLayout.addWidget(self.Phase_label, 0, 0, 1, 1)
        self.Weight_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.Weight_label.setFont(font)
        self.Weight_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Weight_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Weight_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_label.setObjectName("Weight_label")
        self.gridLayout.addWidget(self.Weight_label, 0, 1, 1, 1)
        self.radioButtonStab = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonStab.sizePolicy().hasHeightForWidth())
        self.radioButtonStab.setSizePolicy(sizePolicy)
        self.radioButtonStab.setText("")
        self.radioButtonStab.setCheckable(True)
        self.radioButtonStab.setAutoExclusive(False)
        self.radioButtonStab.setObjectName("radioButtonStab")
        self.gridLayout.addWidget(self.radioButtonStab, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Total_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.Total_label.setFont(font)
        self.Total_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Total_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Total_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Total_label.setObjectName("Total_label")
        self.gridLayout_2.addWidget(self.Total_label, 1, 0, 1, 5)
        self.Par_label = QtWidgets.QLabel(self.page)
        self.Par_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Par_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Par_label.setObjectName("Par_label")
        self.gridLayout_2.addWidget(self.Par_label, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 3, 4, 1, 2)
        self.Doza_label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.Doza_label.setFont(font)
        self.Doza_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Doza_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Doza_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Doza_label.setObjectName("Doza_label")
        self.gridLayout_2.addWidget(self.Doza_label, 0, 0, 1, 6)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 32))
        self.menuBar.setObjectName("menuBar")
        self.menuCLBR = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCLBR.setFont(font)
        self.menuCLBR.setObjectName("menuCLBR")
        self.menuRep = QtWidgets.QMenu(self.menuCLBR)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuRep.setFont(font)
        self.menuRep.setObjectName("menuRep")
        self.menuClb = QtWidgets.QMenu(self.menuCLBR)
        self.menuClb.setObjectName("menuClb")
        self.menuCONF = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCONF.setFont(font)
        self.menuCONF.setObjectName("menuCONF")
        self.menuTIME = QtWidgets.QMenu(self.menuCONF)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuTIME.setFont(font)
        self.menuTIME.setObjectName("menuTIME")
        self.menuWEIGHT = QtWidgets.QMenu(self.menuCONF)
        self.menuWEIGHT.setObjectName("menuWEIGHT")
        self.menuNNN = QtWidgets.QMenu(self.menuCONF)
        self.menuNNN.setObjectName("menuNNN")
        self.menuFLAGS = QtWidgets.QMenu(self.menuCONF)
        self.menuFLAGS.setObjectName("menuFLAGS")
        self.menuOPER = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuOPER.setFont(font)
        self.menuOPER.setObjectName("menuOPER")
        self.menuPORT = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuPORT.setFont(font)
        self.menuPORT.setObjectName("menuPORT")
        self.menuQuit = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuQuit.setFont(font)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRep2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRep2.setFont(font)
        self.actionRep2.setObjectName("actionRep2")
        self.actionRep3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRep3.setFont(font)
        self.actionRep3.setObjectName("actionRep3")
        self.action0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action0.setFont(font)
        self.action0.setObjectName("action0")
        self.action1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action1.setFont(font)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action2.setFont(font)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action3.setFont(font)
        self.action3.setObjectName("action3")
        self.action0_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action0_2.setFont(font)
        self.action0_2.setObjectName("action0_2")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action1_2.setFont(font)
        self.action1_2.setObjectName("action1_2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action2_2.setFont(font)
        self.action2_2.setObjectName("action2_2")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action3_2.setFont(font)
        self.action3_2.setObjectName("action3_2")
        self.actionUnld = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionUnld.setFont(font)
        self.actionUnld.setObjectName("actionUnld")
        self.actionPreFeed = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionPreFeed.setFont(font)
        self.actionPreFeed.setObjectName("actionPreFeed")
        self.actionPreMeas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionPreMeas.setFont(font)
        self.actionPreMeas.setObjectName("actionPreMeas")
        self.actionBtmChk = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionBtmChk.setFont(font)
        self.actionBtmChk.setObjectName("actionBtmChk")
        self.actionShrtTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionShrtTMO.setFont(font)
        self.actionShrtTMO.setObjectName("actionShrtTMO")
        self.actionLongTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionLongTMO.setFont(font)
        self.actionLongTMO.setObjectName("actionLongTMO")
        self.actionSleep = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSleep.setFont(font)
        self.actionSleep.setObjectName("actionSleep")
        self.actionReady = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionReady.setFont(font)
        self.actionReady.setObjectName("actionReady")
        self.actionCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionCycle.setFont(font)
        self.actionCycle.setObjectName("actionCycle")
        self.actionTSmin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionTSmin.setFont(font)
        self.actionTSmin.setObjectName("actionTSmin")
        self.actionDoza = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDoza.setFont(font)
        self.actionDoza.setObjectName("actionDoza")
        self.actionUpr1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionUpr1.setFont(font)
        self.actionUpr1.setObjectName("actionUpr1")
        self.actionUpr2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionUpr2.setFont(font)
        self.actionUpr2.setObjectName("actionUpr2")
        self.actionDozZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDozZ.setFont(font)
        self.actionDozZ.setObjectName("actionDozZ")
        self.actionTarZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionTarZ.setFont(font)
        self.actionTarZ.setObjectName("actionTarZ")
        self.actionDebounce = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDebounce.setFont(font)
        self.actionDebounce.setObjectName("actionDebounce")
        self.actionTareSkip = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionTareSkip.setFont(font)
        self.actionTareSkip.setObjectName("actionTareSkip")
        self.actionAutoCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionAutoCycle.setFont(font)
        self.actionAutoCycle.setObjectName("actionAutoCycle")
        self.actionAutoStart = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionAutoStart.setFont(font)
        self.actionAutoStart.setObjectName("actionAutoStart")
        self.actionFilterNN = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionFilterNN.setFont(font)
        self.actionFilterNN.setObjectName("actionFilterNN")
        self.actionAdapt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionAdapt.setFont(font)
        self.actionAdapt.setObjectName("actionAdapt")
        self.menuRep.addAction(self.action0)
        self.menuRep.addAction(self.action1)
        self.menuRep.addAction(self.action2)
        self.menuRep.addAction(self.action3)
        self.menuClb.addAction(self.action0_2)
        self.menuClb.addAction(self.action1_2)
        self.menuClb.addAction(self.action2_2)
        self.menuClb.addAction(self.action3_2)
        self.menuCLBR.addAction(self.menuRep.menuAction())
        self.menuCLBR.addAction(self.menuClb.menuAction())
        self.menuCLBR.addAction(self.actionRep2)
        self.menuCLBR.addAction(self.actionRep3)
        self.menuTIME.addAction(self.actionUnld)
        self.menuTIME.addAction(self.actionPreFeed)
        self.menuTIME.addAction(self.actionPreMeas)
        self.menuTIME.addAction(self.actionBtmChk)
        self.menuTIME.addAction(self.actionShrtTMO)
        self.menuTIME.addAction(self.actionLongTMO)
        self.menuTIME.addAction(self.actionSleep)
        self.menuTIME.addAction(self.actionReady)
        self.menuTIME.addAction(self.actionCycle)
        self.menuTIME.addAction(self.actionTSmin)
        self.menuWEIGHT.addAction(self.actionDoza)
        self.menuWEIGHT.addAction(self.actionUpr1)
        self.menuWEIGHT.addAction(self.actionUpr2)
        self.menuWEIGHT.addAction(self.actionDozZ)
        self.menuWEIGHT.addAction(self.actionTarZ)
        self.menuNNN.addAction(self.actionDebounce)
        self.menuNNN.addAction(self.actionTareSkip)
        self.menuNNN.addAction(self.actionFilterNN)
        self.menuNNN.addAction(self.actionAdapt)
        self.menuFLAGS.addAction(self.actionAutoCycle)
        self.menuFLAGS.addAction(self.actionAutoStart)
        self.menuCONF.addAction(self.menuTIME.menuAction())
        self.menuCONF.addAction(self.menuWEIGHT.menuAction())
        self.menuCONF.addAction(self.menuNNN.menuAction())
        self.menuCONF.addAction(self.menuFLAGS.menuAction())
        self.menuBar.addAction(self.menuCLBR.menuAction())
        self.menuBar.addAction(self.menuCONF.menuAction())
        self.menuBar.addAction(self.menuOPER.menuAction())
        self.menuBar.addAction(self.menuPORT.menuAction())
        self.menuBar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Phase_label.setText(_translate("MainWindow", "00 : STOP_phase"))
        self.Weight_label.setText(_translate("MainWindow", "-50.00kg"))
        self.Total_label.setText(_translate("MainWindow", "Sum 1234567.89kg"))
        self.Par_label.setText(_translate("MainWindow", "Par 22"))
        self.pushButton.setText(_translate("MainWindow", "ParN"))
        self.pushButton_4.setText(_translate("MainWindow", "ParV"))
        self.pushButton_2.setText(_translate("MainWindow", "Prev"))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.Doza_label.setText(_translate("MainWindow", "Dose  50.00kg"))
        self.label_4.setText(_translate("MainWindow", "123456.789"))
        self.pushButton_9.setText(_translate("MainWindow", "ZERO"))
        self.label_11.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "123456.789"))
        self.label.setText(_translate("MainWindow", "123456.789"))
        self.label_6.setText(_translate("MainWindow", "-1234.56kg"))
        self.label_9.setText(_translate("MainWindow", "PCSN"))
        self.pushButton_7.setText(_translate("MainWindow", "CLBR2"))
        self.label_3.setText(_translate("MainWindow", "123456.789"))
        self.label_12.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "ADC"))
        self.label_5.setText(_translate("MainWindow", "123456.789"))
        self.pushButton_5.setText(_translate("MainWindow", "CLBR0"))
        self.pushButton_8.setText(_translate("MainWindow", "CLBR3"))
        self.pushButton_6.setText(_translate("MainWindow", "CLBR1"))
        self.label_10.setText(_translate("MainWindow", "ROUND"))
        self.menuCLBR.setTitle(_translate("MainWindow", "CLBR"))
        self.menuRep.setTitle(_translate("MainWindow", "Rep"))
        self.menuClb.setTitle(_translate("MainWindow", "Clb"))
        self.menuCONF.setTitle(_translate("MainWindow", "CONF"))
        self.menuTIME.setTitle(_translate("MainWindow", "TIME"))
        self.menuWEIGHT.setTitle(_translate("MainWindow", "WEIGHT"))
        self.menuNNN.setTitle(_translate("MainWindow", "NNN"))
        self.menuFLAGS.setTitle(_translate("MainWindow", "FLAGS"))
        self.menuOPER.setTitle(_translate("MainWindow", "OPER"))
        self.menuPORT.setTitle(_translate("MainWindow", "PORT"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))
        self.actionRep2.setText(_translate("MainWindow", "PcsN"))
        self.actionRep3.setText(_translate("MainWindow", "Round"))
        self.action0.setText(_translate("MainWindow", "0"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action0_2.setText(_translate("MainWindow", "0"))
        self.action1_2.setText(_translate("MainWindow", "1"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action3_2.setText(_translate("MainWindow", "3"))
        self.actionUnld.setText(_translate("MainWindow", "Unld"))
        self.actionPreFeed.setText(_translate("MainWindow", "PreFeed"))
        self.actionPreMeas.setText(_translate("MainWindow", "preMeas"))
        self.actionBtmChk.setText(_translate("MainWindow", "BtmChk"))
        self.actionShrtTMO.setText(_translate("MainWindow", "ShrtTMO"))
        self.actionLongTMO.setText(_translate("MainWindow", "LongTMO"))
        self.actionSleep.setText(_translate("MainWindow", "Sleep"))
        self.actionReady.setText(_translate("MainWindow", "Ready"))
        self.actionCycle.setText(_translate("MainWindow", "Cycle"))
        self.actionTSmin.setText(_translate("MainWindow", "TSmin"))
        self.actionDoza.setText(_translate("MainWindow", "Doza"))
        self.actionUpr1.setText(_translate("MainWindow", "Upr1"))
        self.actionUpr2.setText(_translate("MainWindow", "Upr2"))
        self.actionDozZ.setText(_translate("MainWindow", "DozZ"))
        self.actionTarZ.setText(_translate("MainWindow", "TarZ"))
        self.actionDebounce.setText(_translate("MainWindow", "Debounce"))
        self.actionTareSkip.setText(_translate("MainWindow", "TareSkip"))
        self.actionAutoCycle.setText(_translate("MainWindow", "AutoCycle"))
        self.actionAutoStart.setText(_translate("MainWindow", "AutoStart"))
        self.actionFilterNN.setText(_translate("MainWindow", "FilterNN"))
        self.actionAdapt.setText(_translate("MainWindow", "Adapt"))

