# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(480, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(480, 248))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PhaseLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhaseLabel.sizePolicy().hasHeightForWidth())
        self.PhaseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.PhaseLabel.setFont(font)
        self.PhaseLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PhaseLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PhaseLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PhaseLabel.setObjectName("PhaseLabel")
        self.gridLayout.addWidget(self.PhaseLabel, 0, 0, 1, 1)
        self.WeightLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WeightLabel.sizePolicy().hasHeightForWidth())
        self.WeightLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.WeightLabel.setFont(font)
        self.WeightLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.WeightLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WeightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WeightLabel.setObjectName("WeightLabel")
        self.gridLayout.addWidget(self.WeightLabel, 0, 1, 2, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LevTxtLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevTxtLabel.sizePolicy().hasHeightForWidth())
        self.LevTxtLabel.setSizePolicy(sizePolicy)
        self.LevTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LevTxtLabel.setObjectName("LevTxtLabel")
        self.horizontalLayout_5.addWidget(self.LevTxtLabel)
        self.LevRadioButton0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton0.sizePolicy().hasHeightForWidth())
        self.LevRadioButton0.setSizePolicy(sizePolicy)
        self.LevRadioButton0.setText("")
        self.LevRadioButton0.setCheckable(True)
        self.LevRadioButton0.setAutoExclusive(False)
        self.LevRadioButton0.setObjectName("LevRadioButton0")
        self.horizontalLayout_5.addWidget(self.LevRadioButton0)
        self.LevRadioButton1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton1.sizePolicy().hasHeightForWidth())
        self.LevRadioButton1.setSizePolicy(sizePolicy)
        self.LevRadioButton1.setText("")
        self.LevRadioButton1.setCheckable(True)
        self.LevRadioButton1.setAutoExclusive(False)
        self.LevRadioButton1.setObjectName("LevRadioButton1")
        self.horizontalLayout_5.addWidget(self.LevRadioButton1)
        self.LevRadioButton2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevRadioButton2.sizePolicy().hasHeightForWidth())
        self.LevRadioButton2.setSizePolicy(sizePolicy)
        self.LevRadioButton2.setText("")
        self.LevRadioButton2.setCheckable(True)
        self.LevRadioButton2.setAutoExclusive(False)
        self.LevRadioButton2.setObjectName("LevRadioButton2")
        self.horizontalLayout_5.addWidget(self.LevRadioButton2)
        self.OverRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OverRadioButton.sizePolicy().hasHeightForWidth())
        self.OverRadioButton.setSizePolicy(sizePolicy)
        self.OverRadioButton.setText("")
        self.OverRadioButton.setCheckable(True)
        self.OverRadioButton.setAutoExclusive(False)
        self.OverRadioButton.setObjectName("OverRadioButton")
        self.horizontalLayout_5.addWidget(self.OverRadioButton)
        self.TareRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TareRadioButton.sizePolicy().hasHeightForWidth())
        self.TareRadioButton.setSizePolicy(sizePolicy)
        self.TareRadioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TareRadioButton.setAutoFillBackground(True)
        self.TareRadioButton.setObjectName("TareRadioButton")
        self.horizontalLayout_5.addWidget(self.TareRadioButton)
        self.StabTxtLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StabTxtLabel.sizePolicy().hasHeightForWidth())
        self.StabTxtLabel.setSizePolicy(sizePolicy)
        self.StabTxtLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StabTxtLabel.setObjectName("StabTxtLabel")
        self.horizontalLayout_5.addWidget(self.StabTxtLabel)
        self.StabRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StabRadioButton.sizePolicy().hasHeightForWidth())
        self.StabRadioButton.setSizePolicy(sizePolicy)
        self.StabRadioButton.setText("")
        self.StabRadioButton.setCheckable(True)
        self.StabRadioButton.setAutoExclusive(False)
        self.StabRadioButton.setObjectName("StabRadioButton")
        self.horizontalLayout_5.addWidget(self.StabRadioButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.DosePage = QtWidgets.QWidget()
        self.DosePage.setObjectName("DosePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DosePage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ParsPushButtonR = QtWidgets.QPushButton(self.DosePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParsPushButtonR.setFont(font)
        self.ParsPushButtonR.setObjectName("ParsPushButtonR")
        self.horizontalLayout_3.addWidget(self.ParsPushButtonR)
        spacerItem = QtWidgets.QSpacerItem(58, 43, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.MainTxtLabel = QtWidgets.QLabel(self.DosePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MainTxtLabel.setFont(font)
        self.MainTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTxtLabel.setObjectName("MainTxtLabel")
        self.horizontalLayout_3.addWidget(self.MainTxtLabel)
        spacerItem1 = QtWidgets.QSpacerItem(58, 43, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.LogoPushButtonL = QtWidgets.QPushButton(self.DosePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LogoPushButtonL.setFont(font)
        self.LogoPushButtonL.setObjectName("LogoPushButtonL")
        self.horizontalLayout_3.addWidget(self.LogoPushButtonL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.DoseLabel = QtWidgets.QLabel(self.DosePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DoseLabel.sizePolicy().hasHeightForWidth())
        self.DoseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.DoseLabel.setFont(font)
        self.DoseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DoseLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DoseLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DoseLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DoseLabel.setObjectName("DoseLabel")
        self.horizontalLayout_7.addWidget(self.DoseLabel)
        self.DoseNomPushButton = QtWidgets.QPushButton(self.DosePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DoseNomPushButton.setFont(font)
        self.DoseNomPushButton.setObjectName("DoseNomPushButton")
        self.horizontalLayout_7.addWidget(self.DoseNomPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.TotalLabel = QtWidgets.QLabel(self.DosePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalLabel.sizePolicy().hasHeightForWidth())
        self.TotalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalLabel.setObjectName("TotalLabel")
        self.verticalLayout_2.addWidget(self.TotalLabel)
        self.stackedWidget.addWidget(self.DosePage)
        self.ParsPage = QtWidgets.QWidget()
        self.ParsPage.setObjectName("ParsPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ParsPage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.ParsPage)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ClbrPushButtonR = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbrPushButtonR.setFont(font)
        self.ClbrPushButtonR.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ClbrPushButtonR.setObjectName("ClbrPushButtonR")
        self.horizontalLayout_2.addWidget(self.ClbrPushButtonR)
        spacerItem3 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.ParsTxtLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ParsTxtLabel.setFont(font)
        self.ParsTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ParsTxtLabel.setObjectName("ParsTxtLabel")
        self.horizontalLayout_2.addWidget(self.ParsTxtLabel)
        spacerItem4 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.MainPushButtonL = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MainPushButtonL.setFont(font)
        self.MainPushButtonL.setObjectName("MainPushButtonL")
        self.horizontalLayout_2.addWidget(self.MainPushButtonL)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        self.ParameterLabel = QtWidgets.QLabel(self.ParsPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ParameterLabel.setFont(font)
        self.ParameterLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ParameterLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ParameterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ParameterLabel.setObjectName("ParameterLabel")
        self.gridLayout_5.addWidget(self.ParameterLabel, 1, 0, 1, 1)
        self.ParsWidget = QtWidgets.QWidget(self.ParsPage)
        self.ParsWidget.setObjectName("ParsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ParsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ParNPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParNPushButton.setFont(font)
        self.ParNPushButton.setObjectName("ParNPushButton")
        self.horizontalLayout.addWidget(self.ParNPushButton)
        self.NextPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NextPushButton.setFont(font)
        self.NextPushButton.setObjectName("NextPushButton")
        self.horizontalLayout.addWidget(self.NextPushButton)
        self.PrevPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PrevPushButton.setFont(font)
        self.PrevPushButton.setObjectName("PrevPushButton")
        self.horizontalLayout.addWidget(self.PrevPushButton)
        self.ParVPushButton = QtWidgets.QPushButton(self.ParsWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParVPushButton.setFont(font)
        self.ParVPushButton.setObjectName("ParVPushButton")
        self.horizontalLayout.addWidget(self.ParVPushButton)
        self.gridLayout_5.addWidget(self.ParsWidget, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.ParsPage)
        self.ClbrPage = QtWidgets.QWidget()
        self.ClbrPage.setObjectName("ClbrPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ClbrPage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ManuPushButtonR = QtWidgets.QPushButton(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ManuPushButtonR.setFont(font)
        self.ManuPushButtonR.setObjectName("ManuPushButtonR")
        self.gridLayout_3.addWidget(self.ManuPushButtonR, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.ClbrTxtLabel = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ClbrTxtLabel.setFont(font)
        self.ClbrTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ClbrTxtLabel.setObjectName("ClbrTxtLabel")
        self.gridLayout_3.addWidget(self.ClbrTxtLabel, 0, 2, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(78, 26, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.ParsPushButtonL = QtWidgets.QPushButton(self.ClbrPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ParsPushButtonL.setFont(font)
        self.ParsPushButtonL.setObjectName("ParsPushButtonL")
        self.gridLayout_3.addWidget(self.ParsPushButtonL, 0, 5, 1, 1)
        self.ClbPushButton0 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton0.sizePolicy().hasHeightForWidth())
        self.ClbPushButton0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton0.setFont(font)
        self.ClbPushButton0.setObjectName("ClbPushButton0")
        self.gridLayout_3.addWidget(self.ClbPushButton0, 1, 0, 1, 1)
        self.ClbLabel1 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel1.setFont(font)
        self.ClbLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel1.setObjectName("ClbLabel1")
        self.gridLayout_3.addWidget(self.ClbLabel1, 1, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 3, 1, 1)
        self.ClbPushButton1 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton1.sizePolicy().hasHeightForWidth())
        self.ClbPushButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton1.setFont(font)
        self.ClbPushButton1.setObjectName("ClbPushButton1")
        self.gridLayout_3.addWidget(self.ClbPushButton1, 1, 4, 1, 1)
        self.ClbLabel0 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel0.setFont(font)
        self.ClbLabel0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel0.setObjectName("ClbLabel0")
        self.gridLayout_3.addWidget(self.ClbLabel0, 1, 5, 1, 1)
        self.ClbPushButton2 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton2.sizePolicy().hasHeightForWidth())
        self.ClbPushButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton2.setFont(font)
        self.ClbPushButton2.setObjectName("ClbPushButton2")
        self.gridLayout_3.addWidget(self.ClbPushButton2, 2, 0, 1, 1)
        self.ClbLabel3 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel3.setFont(font)
        self.ClbLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel3.setObjectName("ClbLabel3")
        self.gridLayout_3.addWidget(self.ClbLabel3, 2, 1, 1, 2)
        self.ClbPushButton3 = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClbPushButton3.sizePolicy().hasHeightForWidth())
        self.ClbPushButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbPushButton3.setFont(font)
        self.ClbPushButton3.setObjectName("ClbPushButton3")
        self.gridLayout_3.addWidget(self.ClbPushButton3, 2, 4, 1, 1)
        self.ClbLabel2 = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ClbLabel2.setFont(font)
        self.ClbLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ClbLabel2.setObjectName("ClbLabel2")
        self.gridLayout_3.addWidget(self.ClbLabel2, 2, 5, 1, 1)
        self.AdcTxtLabel = QtWidgets.QLabel(self.ClbrPage)
        self.AdcTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AdcTxtLabel.setObjectName("AdcTxtLabel")
        self.gridLayout_3.addWidget(self.AdcTxtLabel, 3, 0, 1, 1)
        self.AdcCodeLabel = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.AdcCodeLabel.setFont(font)
        self.AdcCodeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AdcCodeLabel.setObjectName("AdcCodeLabel")
        self.gridLayout_3.addWidget(self.AdcCodeLabel, 3, 1, 1, 2)
        self.ZeroPushButton = QtWidgets.QPushButton(self.ClbrPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZeroPushButton.sizePolicy().hasHeightForWidth())
        self.ZeroPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ZeroPushButton.setFont(font)
        self.ZeroPushButton.setObjectName("ZeroPushButton")
        self.gridLayout_3.addWidget(self.ZeroPushButton, 3, 4, 1, 1)
        self.ZeroLabel = QtWidgets.QLabel(self.ClbrPage)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.ZeroLabel.setFont(font)
        self.ZeroLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ZeroLabel.setObjectName("ZeroLabel")
        self.gridLayout_3.addWidget(self.ZeroLabel, 3, 5, 1, 1)
        self.stackedWidget.addWidget(self.ClbrPage)
        self.ManuPage = QtWidgets.QWidget()
        self.ManuPage.setObjectName("ManuPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ManuPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LogoPushButtonR = QtWidgets.QPushButton(self.ManuPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LogoPushButtonR.setFont(font)
        self.LogoPushButtonR.setObjectName("LogoPushButtonR")
        self.horizontalLayout_4.addWidget(self.LogoPushButtonR)
        spacerItem8 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.ManuTxtLabel = QtWidgets.QLabel(self.ManuPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ManuTxtLabel.setFont(font)
        self.ManuTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ManuTxtLabel.setObjectName("ManuTxtLabel")
        self.horizontalLayout_4.addWidget(self.ManuTxtLabel)
        spacerItem9 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.ClbrPushButtonL = QtWidgets.QPushButton(self.ManuPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClbrPushButtonL.setFont(font)
        self.ClbrPushButtonL.setObjectName("ClbrPushButtonL")
        self.horizontalLayout_4.addWidget(self.ClbrPushButtonL)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.InpRadioButton0 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton0.sizePolicy().hasHeightForWidth())
        self.InpRadioButton0.setSizePolicy(sizePolicy)
        self.InpRadioButton0.setObjectName("InpRadioButton0")
        self.horizontalLayout_8.addWidget(self.InpRadioButton0)
        self.InpRadioButton1 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton1.sizePolicy().hasHeightForWidth())
        self.InpRadioButton1.setSizePolicy(sizePolicy)
        self.InpRadioButton1.setObjectName("InpRadioButton1")
        self.horizontalLayout_8.addWidget(self.InpRadioButton1)
        self.InpRadioButton2 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton2.sizePolicy().hasHeightForWidth())
        self.InpRadioButton2.setSizePolicy(sizePolicy)
        self.InpRadioButton2.setObjectName("InpRadioButton2")
        self.horizontalLayout_8.addWidget(self.InpRadioButton2)
        self.InpRadioButton3 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton3.sizePolicy().hasHeightForWidth())
        self.InpRadioButton3.setSizePolicy(sizePolicy)
        self.InpRadioButton3.setObjectName("InpRadioButton3")
        self.horizontalLayout_8.addWidget(self.InpRadioButton3)
        self.InpRadioButton4 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton4.sizePolicy().hasHeightForWidth())
        self.InpRadioButton4.setSizePolicy(sizePolicy)
        self.InpRadioButton4.setObjectName("InpRadioButton4")
        self.horizontalLayout_8.addWidget(self.InpRadioButton4)
        self.InpRadioButton5 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton5.sizePolicy().hasHeightForWidth())
        self.InpRadioButton5.setSizePolicy(sizePolicy)
        self.InpRadioButton5.setObjectName("InpRadioButton5")
        self.horizontalLayout_8.addWidget(self.InpRadioButton5)
        self.InpRadioButton6 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton6.sizePolicy().hasHeightForWidth())
        self.InpRadioButton6.setSizePolicy(sizePolicy)
        self.InpRadioButton6.setObjectName("InpRadioButton6")
        self.horizontalLayout_8.addWidget(self.InpRadioButton6)
        self.InpRadioButton7 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InpRadioButton7.sizePolicy().hasHeightForWidth())
        self.InpRadioButton7.setSizePolicy(sizePolicy)
        self.InpRadioButton7.setObjectName("InpRadioButton7")
        self.horizontalLayout_8.addWidget(self.InpRadioButton7)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.OutRadioButton6 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButton6.sizePolicy().hasHeightForWidth())
        self.OutRadioButton6.setSizePolicy(sizePolicy)
        self.OutRadioButton6.setObjectName("OutRadioButton6")
        self.horizontalLayout_9.addWidget(self.OutRadioButton6)
        self.OutRadioButton7 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButton7.sizePolicy().hasHeightForWidth())
        self.OutRadioButton7.setSizePolicy(sizePolicy)
        self.OutRadioButton7.setObjectName("OutRadioButton7")
        self.horizontalLayout_9.addWidget(self.OutRadioButton7)
        self.OutRadioButton8 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButton8.sizePolicy().hasHeightForWidth())
        self.OutRadioButton8.setSizePolicy(sizePolicy)
        self.OutRadioButton8.setObjectName("OutRadioButton8")
        self.horizontalLayout_9.addWidget(self.OutRadioButton8)
        self.OutRadioButton9 = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButton9.sizePolicy().hasHeightForWidth())
        self.OutRadioButton9.setSizePolicy(sizePolicy)
        self.OutRadioButton9.setObjectName("OutRadioButton9")
        self.horizontalLayout_9.addWidget(self.OutRadioButton9)
        self.OutRadioButtonA = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButtonA.sizePolicy().hasHeightForWidth())
        self.OutRadioButtonA.setSizePolicy(sizePolicy)
        self.OutRadioButtonA.setObjectName("OutRadioButtonA")
        self.horizontalLayout_9.addWidget(self.OutRadioButtonA)
        self.OutRadioButtonB = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButtonB.sizePolicy().hasHeightForWidth())
        self.OutRadioButtonB.setSizePolicy(sizePolicy)
        self.OutRadioButtonB.setObjectName("OutRadioButtonB")
        self.horizontalLayout_9.addWidget(self.OutRadioButtonB)
        self.OutRadioButtonC = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButtonC.sizePolicy().hasHeightForWidth())
        self.OutRadioButtonC.setSizePolicy(sizePolicy)
        self.OutRadioButtonC.setObjectName("OutRadioButtonC")
        self.horizontalLayout_9.addWidget(self.OutRadioButtonC)
        self.OutRadioButtonD = QtWidgets.QRadioButton(self.ManuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutRadioButtonD.sizePolicy().hasHeightForWidth())
        self.OutRadioButtonD.setSizePolicy(sizePolicy)
        self.OutRadioButtonD.setObjectName("OutRadioButtonD")
        self.horizontalLayout_9.addWidget(self.OutRadioButtonD)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.ManuPage)
        self.LogoPage = QtWidgets.QWidget()
        self.LogoPage.setObjectName("LogoPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LogoPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.MainPushButtonR = QtWidgets.QPushButton(self.LogoPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MainPushButtonR.setFont(font)
        self.MainPushButtonR.setObjectName("MainPushButtonR")
        self.horizontalLayout_6.addWidget(self.MainPushButtonR)
        spacerItem10 = QtWidgets.QSpacerItem(58, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.LogoTxtLabel = QtWidgets.QLabel(self.LogoPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LogoTxtLabel.setFont(font)
        self.LogoTxtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LogoTxtLabel.setObjectName("LogoTxtLabel")
        self.horizontalLayout_6.addWidget(self.LogoTxtLabel)
        spacerItem11 = QtWidgets.QSpacerItem(68, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.ManuPushButtonL = QtWidgets.QPushButton(self.LogoPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ManuPushButtonL.setFont(font)
        self.ManuPushButtonL.setObjectName("ManuPushButtonL")
        self.horizontalLayout_6.addWidget(self.ManuPushButtonL)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DvaTxtLabel = QtWidgets.QLabel(self.LogoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DvaTxtLabel.sizePolicy().hasHeightForWidth())
        self.DvaTxtLabel.setSizePolicy(sizePolicy)
        self.DvaTxtLabel.setObjectName("DvaTxtLabel")
        self.gridLayout_4.addWidget(self.DvaTxtLabel, 0, 0, 1, 2)
        self.VersionLabel = QtWidgets.QLabel(self.LogoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VersionLabel.sizePolicy().hasHeightForWidth())
        self.VersionLabel.setSizePolicy(sizePolicy)
        self.VersionLabel.setObjectName("VersionLabel")
        self.gridLayout_4.addWidget(self.VersionLabel, 1, 1, 1, 1)
        self.MasterRadioButton = QtWidgets.QRadioButton(self.LogoPage)
        self.MasterRadioButton.setObjectName("MasterRadioButton")
        self.gridLayout_4.addWidget(self.MasterRadioButton, 1, 0, 1, 1)
        self.CheckSumLabel = QtWidgets.QLabel(self.LogoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckSumLabel.sizePolicy().hasHeightForWidth())
        self.CheckSumLabel.setSizePolicy(sizePolicy)
        self.CheckSumLabel.setObjectName("CheckSumLabel")
        self.gridLayout_4.addWidget(self.CheckSumLabel, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 0, 1, 1)
        self.TokomTxtLabel = QtWidgets.QLabel(self.LogoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TokomTxtLabel.sizePolicy().hasHeightForWidth())
        self.TokomTxtLabel.setSizePolicy(sizePolicy)
        self.TokomTxtLabel.setObjectName("TokomTxtLabel")
        self.gridLayout_4.addWidget(self.TokomTxtLabel, 3, 1, 1, 1)
        self.MailTxtLabel = QtWidgets.QLabel(self.LogoPage)
        self.MailTxtLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MailTxtLabel.setObjectName("MailTxtLabel")
        self.gridLayout_4.addWidget(self.MailTxtLabel, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.LogoPage)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 2)
        self.PhaseLabel.raise_()
        self.stackedWidget.raise_()
        self.WeightLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setObjectName("menuBar")
        self.menuCLBR = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCLBR.setFont(font)
        self.menuCLBR.setObjectName("menuCLBR")
        self.menuRep = QtWidgets.QMenu(self.menuCLBR)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuRep.setFont(font)
        self.menuRep.setObjectName("menuRep")
        self.menuClb = QtWidgets.QMenu(self.menuCLBR)
        self.menuClb.setObjectName("menuClb")
        self.menuCONF = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuCONF.setFont(font)
        self.menuCONF.setObjectName("menuCONF")
        self.menuTIME = QtWidgets.QMenu(self.menuCONF)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuTIME.setFont(font)
        self.menuTIME.setObjectName("menuTIME")
        self.menuWEIGHT = QtWidgets.QMenu(self.menuCONF)
        self.menuWEIGHT.setObjectName("menuWEIGHT")
        self.menuNNN = QtWidgets.QMenu(self.menuCONF)
        self.menuNNN.setObjectName("menuNNN")
        self.menuFLAGS = QtWidgets.QMenu(self.menuCONF)
        self.menuFLAGS.setObjectName("menuFLAGS")
        self.menuOPER = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuOPER.setFont(font)
        self.menuOPER.setObjectName("menuOPER")
        self.menuPORT = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuPORT.setFont(font)
        self.menuPORT.setObjectName("menuPORT")
        self.menuQuit = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuQuit.setFont(font)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menuBar)
        self.PcsNAction = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.PcsNAction.setFont(font)
        self.PcsNAction.setObjectName("PcsNAction")
        self.RoundAction = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RoundAction.setFont(font)
        self.RoundAction.setObjectName("RoundAction")
        self.RepAction0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction0.setFont(font)
        self.RepAction0.setObjectName("RepAction0")
        self.RepAction1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction1.setFont(font)
        self.RepAction1.setObjectName("RepAction1")
        self.RepAction2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction2.setFont(font)
        self.RepAction2.setObjectName("RepAction2")
        self.RepAction3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.RepAction3.setFont(font)
        self.RepAction3.setObjectName("RepAction3")
        self.ClbAction0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction0.setFont(font)
        self.ClbAction0.setObjectName("ClbAction0")
        self.ClbAction1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction1.setFont(font)
        self.ClbAction1.setObjectName("ClbAction1")
        self.ClbAction2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction2.setFont(font)
        self.ClbAction2.setObjectName("ClbAction2")
        self.ClbAction3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.ClbAction3.setFont(font)
        self.ClbAction3.setObjectName("ClbAction3")
        self.actionUnld = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUnld.setFont(font)
        self.actionUnld.setObjectName("actionUnld")
        self.actionPreFeed = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionPreFeed.setFont(font)
        self.actionPreFeed.setObjectName("actionPreFeed")
        self.actionPreMeas = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionPreMeas.setFont(font)
        self.actionPreMeas.setObjectName("actionPreMeas")
        self.actionBtmChk = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionBtmChk.setFont(font)
        self.actionBtmChk.setObjectName("actionBtmChk")
        self.actionShrtTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionShrtTMO.setFont(font)
        self.actionShrtTMO.setObjectName("actionShrtTMO")
        self.actionLongTMO = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionLongTMO.setFont(font)
        self.actionLongTMO.setObjectName("actionLongTMO")
        self.actionSleep = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSleep.setFont(font)
        self.actionSleep.setObjectName("actionSleep")
        self.actionReady = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionReady.setFont(font)
        self.actionReady.setObjectName("actionReady")
        self.actionCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionCycle.setFont(font)
        self.actionCycle.setObjectName("actionCycle")
        self.actionTSmin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTSmin.setFont(font)
        self.actionTSmin.setObjectName("actionTSmin")
        self.actionDoza = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDoza.setFont(font)
        self.actionDoza.setObjectName("actionDoza")
        self.actionUpr1 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUpr1.setFont(font)
        self.actionUpr1.setObjectName("actionUpr1")
        self.actionUpr2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionUpr2.setFont(font)
        self.actionUpr2.setObjectName("actionUpr2")
        self.actionDozZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDozZ.setFont(font)
        self.actionDozZ.setObjectName("actionDozZ")
        self.actionTarZ = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTarZ.setFont(font)
        self.actionTarZ.setObjectName("actionTarZ")
        self.actionDebounce = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionDebounce.setFont(font)
        self.actionDebounce.setObjectName("actionDebounce")
        self.actionTareSkip = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionTareSkip.setFont(font)
        self.actionTareSkip.setObjectName("actionTareSkip")
        self.actionAutoCycle = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAutoCycle.setFont(font)
        self.actionAutoCycle.setObjectName("actionAutoCycle")
        self.actionAutoStart = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAutoStart.setFont(font)
        self.actionAutoStart.setObjectName("actionAutoStart")
        self.actionFilterNN = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionFilterNN.setFont(font)
        self.actionFilterNN.setObjectName("actionFilterNN")
        self.actionAdapt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAdapt.setFont(font)
        self.actionAdapt.setObjectName("actionAdapt")
        self.MasterAction = QtWidgets.QAction(MainWindow)
        self.MasterAction.setObjectName("MasterAction")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuRep.addAction(self.RepAction0)
        self.menuRep.addAction(self.RepAction1)
        self.menuRep.addAction(self.RepAction2)
        self.menuRep.addAction(self.RepAction3)
        self.menuClb.addAction(self.ClbAction0)
        self.menuClb.addAction(self.ClbAction1)
        self.menuClb.addAction(self.ClbAction2)
        self.menuClb.addAction(self.ClbAction3)
        self.menuCLBR.addAction(self.menuRep.menuAction())
        self.menuCLBR.addAction(self.menuClb.menuAction())
        self.menuCLBR.addAction(self.PcsNAction)
        self.menuCLBR.addAction(self.RoundAction)
        self.menuCLBR.addAction(self.MasterAction)
        self.menuTIME.addAction(self.actionUnld)
        self.menuTIME.addAction(self.actionPreFeed)
        self.menuTIME.addAction(self.actionPreMeas)
        self.menuTIME.addAction(self.actionBtmChk)
        self.menuTIME.addAction(self.actionShrtTMO)
        self.menuTIME.addAction(self.actionLongTMO)
        self.menuTIME.addAction(self.actionSleep)
        self.menuTIME.addAction(self.actionReady)
        self.menuTIME.addAction(self.actionCycle)
        self.menuTIME.addAction(self.actionTSmin)
        self.menuWEIGHT.addAction(self.actionDoza)
        self.menuWEIGHT.addAction(self.actionUpr1)
        self.menuWEIGHT.addAction(self.actionUpr2)
        self.menuWEIGHT.addAction(self.actionDozZ)
        self.menuWEIGHT.addAction(self.actionTarZ)
        self.menuNNN.addAction(self.actionDebounce)
        self.menuNNN.addAction(self.actionTareSkip)
        self.menuNNN.addAction(self.actionFilterNN)
        self.menuNNN.addAction(self.actionAdapt)
        self.menuFLAGS.addAction(self.actionAutoCycle)
        self.menuFLAGS.addAction(self.actionAutoStart)
        self.menuCONF.addAction(self.menuTIME.menuAction())
        self.menuCONF.addAction(self.menuWEIGHT.menuAction())
        self.menuCONF.addAction(self.menuNNN.menuAction())
        self.menuCONF.addAction(self.menuFLAGS.menuAction())
        self.menuQuit.addAction(self.actionAbout)
        self.menuQuit.addAction(self.actionExit)
        self.menuBar.addAction(self.menuCLBR.menuAction())
        self.menuBar.addAction(self.menuCONF.menuAction())
        self.menuBar.addAction(self.menuOPER.menuAction())
        self.menuBar.addAction(self.menuPORT.menuAction())
        self.menuBar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PhaseLabel.setText(_translate("MainWindow", "00 : STOP_phase-bla-bla"))
        self.WeightLabel.setText(_translate("MainWindow", "-50.00kg"))
        self.LevTxtLabel.setText(_translate("MainWindow", "LEV"))
        self.TareRadioButton.setToolTip(_translate("MainWindow", "Fix tare"))
        self.TareRadioButton.setText(_translate("MainWindow", "TAR"))
        self.StabTxtLabel.setText(_translate("MainWindow", "STB"))
        self.ParsPushButtonR.setText(_translate("MainWindow", "PARS"))
        self.MainTxtLabel.setText(_translate("MainWindow", "MAIN"))
        self.LogoPushButtonL.setText(_translate("MainWindow", "LOGO"))
        self.DoseLabel.setText(_translate("MainWindow", "50.00kg"))
        self.DoseNomPushButton.setText(_translate("MainWindow", "Dose Nominal"))
        self.TotalLabel.setText(_translate("MainWindow", "Total 1234567.89kg"))
        self.ClbrPushButtonR.setText(_translate("MainWindow", "CLBR"))
        self.ParsTxtLabel.setText(_translate("MainWindow", "PARAMS"))
        self.MainPushButtonL.setText(_translate("MainWindow", "MAIN"))
        self.ParameterLabel.setText(_translate("MainWindow", "22: name of parameter:   -999999999 "))
        self.ParNPushButton.setText(_translate("MainWindow", "PAR N"))
        self.NextPushButton.setText(_translate("MainWindow", "NEXT"))
        self.PrevPushButton.setText(_translate("MainWindow", "PREV"))
        self.ParVPushButton.setText(_translate("MainWindow", "PAR V"))
        self.ManuPushButtonR.setText(_translate("MainWindow", "MANU"))
        self.ClbrTxtLabel.setText(_translate("MainWindow", "CLBR"))
        self.ParsPushButtonL.setText(_translate("MainWindow", "PARS"))
        self.ClbPushButton0.setText(_translate("MainWindow", "CLBR0"))
        self.ClbLabel1.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton1.setText(_translate("MainWindow", "CLBR1"))
        self.ClbLabel0.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton2.setText(_translate("MainWindow", "CLBR2"))
        self.ClbLabel3.setText(_translate("MainWindow", "123456.789"))
        self.ClbPushButton3.setText(_translate("MainWindow", "CLBR3"))
        self.ClbLabel2.setText(_translate("MainWindow", "123456.789"))
        self.AdcTxtLabel.setText(_translate("MainWindow", "ADC"))
        self.AdcCodeLabel.setText(_translate("MainWindow", "123456.789"))
        self.ZeroPushButton.setText(_translate("MainWindow", "ZERO"))
        self.ZeroLabel.setText(_translate("MainWindow", "-1234.56kg"))
        self.LogoPushButtonR.setText(_translate("MainWindow", "LOGO"))
        self.ManuTxtLabel.setText(_translate("MainWindow", "MANUAL"))
        self.ClbrPushButtonL.setText(_translate("MainWindow", "CLBR"))
        self.InpRadioButton0.setText(_translate("MainWindow", "i0"))
        self.InpRadioButton1.setText(_translate("MainWindow", "i1"))
        self.InpRadioButton2.setText(_translate("MainWindow", "i2"))
        self.InpRadioButton3.setText(_translate("MainWindow", "i3"))
        self.InpRadioButton4.setText(_translate("MainWindow", "i4"))
        self.InpRadioButton5.setText(_translate("MainWindow", "i5"))
        self.InpRadioButton6.setText(_translate("MainWindow", "i6"))
        self.InpRadioButton7.setText(_translate("MainWindow", "i7"))
        self.OutRadioButton6.setText(_translate("MainWindow", "o6"))
        self.OutRadioButton7.setText(_translate("MainWindow", "o7"))
        self.OutRadioButton8.setText(_translate("MainWindow", "o8"))
        self.OutRadioButton9.setText(_translate("MainWindow", "o9"))
        self.OutRadioButtonA.setText(_translate("MainWindow", "oA"))
        self.OutRadioButtonB.setText(_translate("MainWindow", "oB"))
        self.OutRadioButtonC.setText(_translate("MainWindow", "oC"))
        self.OutRadioButtonD.setText(_translate("MainWindow", "oD"))
        self.MainPushButtonR.setText(_translate("MainWindow", "MAIN"))
        self.LogoTxtLabel.setText(_translate("MainWindow", "LOGO"))
        self.ManuPushButtonL.setText(_translate("MainWindow", "MANU"))
        self.DvaTxtLabel.setText(_translate("MainWindow", "DVA TKM16 Batch Weigher Controler"))
        self.VersionLabel.setText(_translate("MainWindow", "Program version 32"))
        self.MasterRadioButton.setText(_translate("MainWindow", "Master Bit"))
        self.CheckSumLabel.setText(_translate("MainWindow", "Check sum 0xABCD"))
        self.TokomTxtLabel.setText(_translate("MainWindow", "TOKOM, Kyiv-2018"))
        self.MailTxtLabel.setText(_translate("MainWindow", "tokom2009@gmail.com"))
        self.menuCLBR.setTitle(_translate("MainWindow", "CLBR"))
        self.menuRep.setTitle(_translate("MainWindow", "Rep"))
        self.menuClb.setTitle(_translate("MainWindow", "Clb"))
        self.menuCONF.setTitle(_translate("MainWindow", "CONF"))
        self.menuTIME.setTitle(_translate("MainWindow", "TIME"))
        self.menuWEIGHT.setTitle(_translate("MainWindow", "WEIGHT"))
        self.menuNNN.setTitle(_translate("MainWindow", "NNN"))
        self.menuFLAGS.setTitle(_translate("MainWindow", "FLAGS"))
        self.menuOPER.setTitle(_translate("MainWindow", "OPER"))
        self.menuPORT.setTitle(_translate("MainWindow", "PORT"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))
        self.PcsNAction.setText(_translate("MainWindow", "PcsN"))
        self.RoundAction.setText(_translate("MainWindow", "Round"))
        self.RepAction0.setText(_translate("MainWindow", "0"))
        self.RepAction1.setText(_translate("MainWindow", "1"))
        self.RepAction2.setText(_translate("MainWindow", "2"))
        self.RepAction3.setText(_translate("MainWindow", "3"))
        self.ClbAction0.setText(_translate("MainWindow", "0"))
        self.ClbAction1.setText(_translate("MainWindow", "1"))
        self.ClbAction2.setText(_translate("MainWindow", "2"))
        self.ClbAction3.setText(_translate("MainWindow", "3"))
        self.actionUnld.setText(_translate("MainWindow", "Unld"))
        self.actionPreFeed.setText(_translate("MainWindow", "PreFeed"))
        self.actionPreMeas.setText(_translate("MainWindow", "preMeas"))
        self.actionBtmChk.setText(_translate("MainWindow", "BtmChk"))
        self.actionShrtTMO.setText(_translate("MainWindow", "ShrtTMO"))
        self.actionLongTMO.setText(_translate("MainWindow", "LongTMO"))
        self.actionSleep.setText(_translate("MainWindow", "Sleep"))
        self.actionReady.setText(_translate("MainWindow", "Ready"))
        self.actionCycle.setText(_translate("MainWindow", "Cycle"))
        self.actionTSmin.setText(_translate("MainWindow", "TSmin"))
        self.actionDoza.setText(_translate("MainWindow", "Doza"))
        self.actionUpr1.setText(_translate("MainWindow", "Upr1"))
        self.actionUpr2.setText(_translate("MainWindow", "Upr2"))
        self.actionDozZ.setText(_translate("MainWindow", "DozZ"))
        self.actionTarZ.setText(_translate("MainWindow", "TarZ"))
        self.actionDebounce.setText(_translate("MainWindow", "Debounce"))
        self.actionTareSkip.setText(_translate("MainWindow", "TareSkip"))
        self.actionAutoCycle.setText(_translate("MainWindow", "AutoCycle"))
        self.actionAutoStart.setText(_translate("MainWindow", "AutoStart"))
        self.actionFilterNN.setText(_translate("MainWindow", "FilterNN"))
        self.actionAdapt.setText(_translate("MainWindow", "Adapt"))
        self.MasterAction.setText(_translate("MainWindow", "Master Bit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

