		
        zero = rg[adcRg['ZERO'][0]]
        txt = form.format(zero * decimal)
        self.lineEditZero.setText(txt)
        if zero == 0:
            self.radioButtonZero.setChecked(False)
        else:
            self.radioButtonZero.setChecked(True)
        self.radioButtonFast.setChecked(ctrlRg & adcBit['FASTMSK'])

        self.labelVersVal.setText("{:5d}".format(rg[adcRg['V_SN'][0]]))
        self.lineEditLev0.setText("{:5d} ".format(rg[adcRg['LEV0'][0]]))
        self.lineEditLev1.setText("{:5d} ".format(rg[adcRg['LEV1'][0]]))
        self.lineEditLev2.setText("{:5d} ".format(rg[adcRg['LEV2'][0]]))
        self.lineEditScale.setText("{:5d} ".format(rg[adcRg['SCALE'][0]]))
        self.lineEditStab.setText("{:5d} ".format(rg[adcRg['STAB'][0]]))
        self.labelCashVal.setText("0x{:08X}".format(0xFFFFFFFF & rg[adcRg['CASH'][0]]))
        self.labelTotNVal.setText("{:9d}".format(rg[adcRg['TOTN'][0]]))
        self.labelStatusVal.setText("0x{:04x}".format(statusRg))
        self.labelErrorsVal.setText("0x{:04x}".format(rg[adcRg['ERROR'][0]]))
        self.labelPhaseVal.setText("Phase: " + phaseText[rg[adcRg['PHASE'][0]]])
        self.lineEditCtrl.setText("0x{:04X}".format(ctrlRg))
        self.labelDirVal.setText("0x{:04X}".format(rg[adcRg['DIRR'][0]]))
        self.labelDioVal.setText("0x{:04X} / {:05d}".format(rg[adcRg['DIO'][0]], rg[adcRg['DIO'][0]]))
        self.labelFltrVal.setText("{:02d}".format(rg[adcRg['FLTR'][0]]))
        self.labelCycleVal.setText("{:02d}".format(rg[adcRg['CYCLE'][0]]))

        self.lineEditClb0.setText("{:9d}".format(rg[adcRg['CLB0'][0]]))
        self.lineEditClb1.setText("{:9d}".format(rg[adcRg['CLB1'][0]]))
        self.lineEditClb2.setText("{:9d}".format(rg[adcRg['CLB2'][0]]))
        self.lineEditClb3.setText("{:9d}".format(rg[adcRg['CLB3'][0]]))
        self.labelAdcVal.setText("{:9d}".format(rg[adcRg['ADC'][0]]))
        self.lineEditRep0.setText("{:5d}".format(rg[adcRg['REP0'][0]]))
        self.lineEditRep1.setText("{:5d}".format(rg[adcRg['REP1'][0]]))
        self.lineEditRep2.setText("{:5d}".format(rg[adcRg['REP2'][0]]))
        self.lineEditRep3.setText("{:5d}".format(rg[adcRg['REP3'][0]]))
        self.lineEditPcn.setText("{:5d}".format(rg[adcRg['PCSN'][0]]))
        self.lineEditRnd.setText("{:5d}".format(rg[adcRg['ROUND'][0]]))
        self.lineEditRs485.setText("{:5d}".format(rg[adcRg['RS485'][0]]))

        self.lineEditTunld.setText("{:5d}".format(rg[adcRg['TUNLD'][0]]))
        self.lineEditTfeed.setText("{:5d}".format(rg[adcRg['TFEED'][0]]))
        self.lineEditTmeas.setText("{:5d}".format(rg[adcRg['TMEAS'][0]]))
        self.lineEditTbtm.setText("{:5d}".format(rg[adcRg['TBTM'][0]]))
        self.lineEditTdiag.setText("{:5d}".format(rg[adcRg['TDIAG'][0]]))
        self.lineEditTshrt.setText("{:5d}".format(rg[adcRg['TSHRT'][0]]))
        self.lineEditTlong.setText("{:5d}".format(rg[adcRg['TLONG'][0]]))
        self.lineEditTsleep.setText("{:5d}".format(rg[adcRg['TSLP'][0]]))
        self.lineEditTrdy.setText("{:5d}".format(rg[adcRg['TRDY'][0]]))
        self.lineEditTcycle.setText("{:5d}".format(rg[adcRg['TCYCL'][0]]))

        self.lineEditDebounce.setText("{:5d}".format(rg[adcRg['TKEYS'][0]]))
        self.lineEditAuto.setText("{:5d}".format(rg[adcRg['AUTOS'][0]]))
        self.lineEditNskip.setText("{:5d}".format(rg[adcRg['NSKIP'][0]]))
        self.lineEditTareZ.setText("{:5d}".format(rg[adcRg['TARZN'][0]]))

        self.lineEditDoza1.setText("{:5d}".format(rg[adcRg['DOZA1'][0]]))
        self.lineEditDoza2.setText("{:5d}".format(rg[adcRg['DOZA2'][0]]))
        self.lineEditUpr11.setText("{:5d}".format(rg[adcRg['UPR11'][0]]))
        self.lineEditUpr12.setText("{:5d}".format(rg[adcRg['UPR12'][0]]))
        self.lineEditUpr21.setText("{:5d}".format(rg[adcRg['UPR21'][0]]))
        self.lineEditUpr22.setText("{:5d}".format(rg[adcRg['UPR22'][0]]))
        self.lineEditFfa1.setText("{:5d}".format(rg[adcRg['FFA1'][0]]))
        self.lineEditFfa2.setText("{:5d}".format(rg[adcRg['FFA2'][0]]))
        self.lineEditOpen1.setText("{:5d}".format(rg[adcRg['TOPN1'][0]]))
        self.lineEditOpen2.setText("{:5d}".format(rg[adcRg['TOPN2'][0]]))
        self.lineEditTsmin1.setText("{:5d}".format(rg[adcRg['TMIN1'][0]]))
        self.lineEditTsmin2.setText("{:5d}".format(rg[adcRg['TMIN2'][0]]))
        self.lineEditDozz1.setText("{:5d}".format(rg[adcRg['DOZZ1'][0]]))
        self.lineEditDozz2.setText("{:5d}".format(rg[adcRg['DOZZ2'][0]]))
