# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_numpad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Numpad(object):
    def setupUi(self, Numpad):
        Numpad.setObjectName("Numpad")
        Numpad.setWindowModality(QtCore.Qt.ApplicationModal)
        Numpad.resize(378, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Numpad.sizePolicy().hasHeightForWidth())
        Numpad.setSizePolicy(sizePolicy)
        Numpad.setMaximumSize(QtCore.QSize(400, 290))
        self.gridLayout_2 = QtWidgets.QGridLayout(Numpad)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.pb1 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb1.sizePolicy().hasHeightForWidth())
        self.pb1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb1.setFont(font)
        self.pb1.setObjectName("pb1")
        self.grid_layout.addWidget(self.pb1, 2, 0, 1, 1)
        self.pb0 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb0.sizePolicy().hasHeightForWidth())
        self.pb0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb0.setFont(font)
        self.pb0.setObjectName("pb0")
        self.grid_layout.addWidget(self.pb0, 3, 0, 1, 1)
        self.pb_sign = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_sign.sizePolicy().hasHeightForWidth())
        self.pb_sign.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_sign.setFont(font)
        self.pb_sign.setObjectName("pb_sign")
        self.grid_layout.addWidget(self.pb_sign, 3, 1, 1, 1)
        self.pb_pnt = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_pnt.sizePolicy().hasHeightForWidth())
        self.pb_pnt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_pnt.setFont(font)
        self.pb_pnt.setObjectName("pb_pnt")
        self.grid_layout.addWidget(self.pb_pnt, 3, 2, 1, 1)
        self.pb5 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb5.sizePolicy().hasHeightForWidth())
        self.pb5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb5.setFont(font)
        self.pb5.setObjectName("pb5")
        self.grid_layout.addWidget(self.pb5, 1, 1, 1, 1)
        self.pb8 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb8.sizePolicy().hasHeightForWidth())
        self.pb8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb8.setFont(font)
        self.pb8.setObjectName("pb8")
        self.grid_layout.addWidget(self.pb8, 0, 1, 1, 1)
        self.pb9 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb9.sizePolicy().hasHeightForWidth())
        self.pb9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb9.setFont(font)
        self.pb9.setObjectName("pb9")
        self.grid_layout.addWidget(self.pb9, 0, 2, 1, 1)
        self.pb4 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb4.sizePolicy().hasHeightForWidth())
        self.pb4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb4.setFont(font)
        self.pb4.setObjectName("pb4")
        self.grid_layout.addWidget(self.pb4, 1, 0, 1, 1)
        self.pb2 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb2.sizePolicy().hasHeightForWidth())
        self.pb2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb2.setFont(font)
        self.pb2.setObjectName("pb2")
        self.grid_layout.addWidget(self.pb2, 2, 1, 1, 1)
        self.pb6 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb6.sizePolicy().hasHeightForWidth())
        self.pb6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb6.setFont(font)
        self.pb6.setObjectName("pb6")
        self.grid_layout.addWidget(self.pb6, 1, 2, 1, 1)
        self.pb3 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb3.sizePolicy().hasHeightForWidth())
        self.pb3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb3.setFont(font)
        self.pb3.setObjectName("pb3")
        self.grid_layout.addWidget(self.pb3, 2, 2, 1, 1)
        self.pb7 = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb7.sizePolicy().hasHeightForWidth())
        self.pb7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb7.setFont(font)
        self.pb7.setObjectName("pb7")
        self.grid_layout.addWidget(self.pb7, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.grid_layout, 2, 0, 3, 1)
        self.pb_yes = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_yes.sizePolicy().hasHeightForWidth())
        self.pb_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_yes.setFont(font)
        self.pb_yes.setObjectName("pb_yes")
        self.gridLayout_2.addWidget(self.pb_yes, 2, 1, 1, 1)
        self.pb_no = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_no.sizePolicy().hasHeightForWidth())
        self.pb_no.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_no.setFont(font)
        self.pb_no.setObjectName("pb_no")
        self.gridLayout_2.addWidget(self.pb_no, 3, 1, 1, 1)
        self.pb_del = QtWidgets.QPushButton(Numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_del.sizePolicy().hasHeightForWidth())
        self.pb_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_del.setFont(font)
        self.pb_del.setObjectName("pb_del")
        self.gridLayout_2.addWidget(self.pb_del, 4, 1, 1, 1)
        self.lab_rng = QtWidgets.QLabel(Numpad)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_rng.setFont(font)
        self.lab_rng.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_rng.setObjectName("lab_rng")
        self.gridLayout_2.addWidget(self.lab_rng, 0, 0, 1, 2)
        self.lab_val = QtWidgets.QLabel(Numpad)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_val.setFont(font)
        self.lab_val.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_val.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_val.setObjectName("lab_val")
        self.gridLayout_2.addWidget(self.lab_val, 1, 0, 1, 2)

        self.retranslateUi(Numpad)
        QtCore.QMetaObject.connectSlotsByName(Numpad)

    def retranslateUi(self, Numpad):
        _translate = QtCore.QCoreApplication.translate
        Numpad.setWindowTitle(_translate("Numpad", "Numpad"))
        self.pb1.setText(_translate("Numpad", "1"))
        self.pb0.setText(_translate("Numpad", "0"))
        self.pb_sign.setText(_translate("Numpad", "+/-"))
        self.pb_pnt.setText(_translate("Numpad", "."))
        self.pb5.setText(_translate("Numpad", "5"))
        self.pb8.setText(_translate("Numpad", "8"))
        self.pb9.setText(_translate("Numpad", "9"))
        self.pb4.setText(_translate("Numpad", "4"))
        self.pb2.setText(_translate("Numpad", "2"))
        self.pb6.setText(_translate("Numpad", "6"))
        self.pb3.setText(_translate("Numpad", "3"))
        self.pb7.setText(_translate("Numpad", "7"))
        self.pb_yes.setText(_translate("Numpad", "YES"))
        self.pb_no.setText(_translate("Numpad", "NO"))
        self.pb_del.setText(_translate("Numpad", "DEL"))
        self.lab_rng.setText(_translate("Numpad", " -999999999 ... 999999999"))
        self.lab_val.setText(_translate("Numpad", "-1234567890"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Numpad = QtWidgets.QDialog()
    ui = Ui_Numpad()
    ui.setupUi(Numpad)
    Numpad.show()
    sys.exit(app.exec_())

