# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(480, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Window.sizePolicy().hasHeightForWidth())
        Window.setSizePolicy(sizePolicy)
        Window.setMaximumSize(QtCore.QSize(480, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        Window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(480, 248))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_phase = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_phase.sizePolicy().hasHeightForWidth())
        self.lab_phase.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.lab_phase.setFont(font)
        self.lab_phase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_phase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_phase.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_phase.setObjectName("lab_phase")
        self.gridLayout.addWidget(self.lab_phase, 0, 0, 1, 1)
        self.lab_weight = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_weight.sizePolicy().hasHeightForWidth())
        self.lab_weight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(28)
        self.lab_weight.setFont(font)
        self.lab_weight.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_weight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_weight.setObjectName("lab_weight")
        self.gridLayout.addWidget(self.lab_weight, 0, 1, 2, 1)
        self.hl_leds = QtWidgets.QHBoxLayout()
        self.hl_leds.setObjectName("hl_leds")
        self.lab_lev = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_lev.sizePolicy().hasHeightForWidth())
        self.lab_lev.setSizePolicy(sizePolicy)
        self.lab_lev.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_lev.setObjectName("lab_lev")
        self.hl_leds.addWidget(self.lab_lev)
        self.rb_lev0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_lev0.sizePolicy().hasHeightForWidth())
        self.rb_lev0.setSizePolicy(sizePolicy)
        self.rb_lev0.setText("")
        self.rb_lev0.setCheckable(True)
        self.rb_lev0.setAutoExclusive(False)
        self.rb_lev0.setObjectName("rb_lev0")
        self.hl_leds.addWidget(self.rb_lev0)
        self.rb_lev1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_lev1.sizePolicy().hasHeightForWidth())
        self.rb_lev1.setSizePolicy(sizePolicy)
        self.rb_lev1.setText("")
        self.rb_lev1.setCheckable(True)
        self.rb_lev1.setAutoExclusive(False)
        self.rb_lev1.setObjectName("rb_lev1")
        self.hl_leds.addWidget(self.rb_lev1)
        self.rb_lev2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_lev2.sizePolicy().hasHeightForWidth())
        self.rb_lev2.setSizePolicy(sizePolicy)
        self.rb_lev2.setText("")
        self.rb_lev2.setCheckable(True)
        self.rb_lev2.setAutoExclusive(False)
        self.rb_lev2.setObjectName("rb_lev2")
        self.hl_leds.addWidget(self.rb_lev2)
        self.rb_over = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_over.sizePolicy().hasHeightForWidth())
        self.rb_over.setSizePolicy(sizePolicy)
        self.rb_over.setText("")
        self.rb_over.setCheckable(True)
        self.rb_over.setAutoExclusive(False)
        self.rb_over.setObjectName("rb_over")
        self.hl_leds.addWidget(self.rb_over)
        self.rb_tare = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_tare.sizePolicy().hasHeightForWidth())
        self.rb_tare.setSizePolicy(sizePolicy)
        self.rb_tare.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rb_tare.setAutoFillBackground(True)
        self.rb_tare.setObjectName("rb_tare")
        self.hl_leds.addWidget(self.rb_tare)
        self.lab_stab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_stab.sizePolicy().hasHeightForWidth())
        self.lab_stab.setSizePolicy(sizePolicy)
        self.lab_stab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_stab.setObjectName("lab_stab")
        self.hl_leds.addWidget(self.lab_stab)
        self.rb_stab = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_stab.sizePolicy().hasHeightForWidth())
        self.rb_stab.setSizePolicy(sizePolicy)
        self.rb_stab.setText("")
        self.rb_stab.setCheckable(True)
        self.rb_stab.setAutoExclusive(False)
        self.rb_stab.setObjectName("rb_stab")
        self.hl_leds.addWidget(self.rb_stab)
        self.gridLayout.addLayout(self.hl_leds, 1, 0, 1, 1)
        self.sw_pages = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sw_pages.sizePolicy().hasHeightForWidth())
        self.sw_pages.setSizePolicy(sizePolicy)
        self.sw_pages.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.sw_pages.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sw_pages.setFrameShape(QtWidgets.QFrame.Box)
        self.sw_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sw_pages.setObjectName("sw_pages")
        self.dose_page = QtWidgets.QWidget()
        self.dose_page.setObjectName("dose_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dose_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_main = QtWidgets.QHBoxLayout()
        self.hl_main.setObjectName("hl_main")
        self.pb_pars_right = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_pars_right.setFont(font)
        self.pb_pars_right.setObjectName("pb_pars_right")
        self.hl_main.addWidget(self.pb_pars_right)
        spacerItem = QtWidgets.QSpacerItem(58, 43, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_main.addItem(spacerItem)
        self.lab_main = QtWidgets.QLabel(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_main.setFont(font)
        self.lab_main.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_main.setObjectName("lab_main")
        self.hl_main.addWidget(self.lab_main)
        spacerItem1 = QtWidgets.QSpacerItem(58, 43, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_main.addItem(spacerItem1)
        self.pb_logo_left = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_logo_left.setFont(font)
        self.pb_logo_left.setObjectName("pb_logo_left")
        self.hl_main.addWidget(self.pb_logo_left)
        self.verticalLayout_2.addLayout(self.hl_main)
        self.hl_dos_nom = QtWidgets.QHBoxLayout()
        self.hl_dos_nom.setObjectName("hl_dos_nom")
        self.lab_dose = QtWidgets.QLabel(self.dose_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_dose.sizePolicy().hasHeightForWidth())
        self.lab_dose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(20)
        self.lab_dose.setFont(font)
        self.lab_dose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_dose.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_dose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_dose.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_dose.setObjectName("lab_dose")
        self.hl_dos_nom.addWidget(self.lab_dose)
        self.pb_dose_nom = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_dose_nom.setFont(font)
        self.pb_dose_nom.setObjectName("pb_dose_nom")
        self.hl_dos_nom.addWidget(self.pb_dose_nom)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_dos_nom.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hl_dos_nom)
        self.lab_total = QtWidgets.QLabel(self.dose_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_total.sizePolicy().hasHeightForWidth())
        self.lab_total.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(20)
        self.lab_total.setFont(font)
        self.lab_total.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_total.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_total.setObjectName("lab_total")
        self.verticalLayout_2.addWidget(self.lab_total)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pb_unload = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_unload.setFont(font)
        self.pb_unload.setObjectName("pb_unload")
        self.horizontalLayout_7.addWidget(self.pb_unload)
        self.pb_stop = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_stop.setFont(font)
        self.pb_stop.setObjectName("pb_stop")
        self.horizontalLayout_7.addWidget(self.pb_stop)
        self.pb_run = QtWidgets.QPushButton(self.dose_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_run.setFont(font)
        self.pb_run.setObjectName("pb_run")
        self.horizontalLayout_7.addWidget(self.pb_run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.sw_pages.addWidget(self.dose_page)
        self.pars_page = QtWidgets.QWidget()
        self.pars_page.setObjectName("pars_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pars_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_clbr_right = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clbr_right.setFont(font)
        self.pb_clbr_right.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pb_clbr_right.setObjectName("pb_clbr_right")
        self.horizontalLayout_2.addWidget(self.pb_clbr_right)
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lab_pars = QtWidgets.QLabel(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_pars.setFont(font)
        self.lab_pars.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_pars.setObjectName("lab_pars")
        self.horizontalLayout_2.addWidget(self.lab_pars)
        spacerItem4 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pb_main_left = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_main_left.setFont(font)
        self.pb_main_left.setObjectName("pb_main_left")
        self.horizontalLayout_2.addWidget(self.pb_main_left)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lab_parameter = QtWidgets.QLabel(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lab_parameter.setFont(font)
        self.lab_parameter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_parameter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_parameter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_parameter.setObjectName("lab_parameter")
        self.horizontalLayout_8.addWidget(self.lab_parameter)
        self.lab_parname = QtWidgets.QLabel(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lab_parname.setFont(font)
        self.lab_parname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lab_parname.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_parname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_parname.setObjectName("lab_parname")
        self.horizontalLayout_8.addWidget(self.lab_parname)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_next = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_next.setFont(font)
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout.addWidget(self.pb_next)
        self.pb_prev = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_prev.setFont(font)
        self.pb_prev.setObjectName("pb_prev")
        self.horizontalLayout.addWidget(self.pb_prev)
        self.pb_parv = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_parv.setFont(font)
        self.pb_parv.setObjectName("pb_parv")
        self.horizontalLayout.addWidget(self.pb_parv)
        self.pb_parn = QtWidgets.QPushButton(self.pars_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_parn.setFont(font)
        self.pb_parn.setObjectName("pb_parn")
        self.horizontalLayout.addWidget(self.pb_parn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.sw_pages.addWidget(self.pars_page)
        self.clbr_page = QtWidgets.QWidget()
        self.clbr_page.setObjectName("clbr_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.clbr_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_manu_right = QtWidgets.QPushButton(self.clbr_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_manu_right.setFont(font)
        self.pb_manu_right.setObjectName("pb_manu_right")
        self.horizontalLayout_3.addWidget(self.pb_manu_right)
        spacerItem5 = QtWidgets.QSpacerItem(78, 26, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.lab_clbr = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_clbr.setFont(font)
        self.lab_clbr.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_clbr.setObjectName("lab_clbr")
        self.horizontalLayout_3.addWidget(self.lab_clbr)
        spacerItem6 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pb_pars_left = QtWidgets.QPushButton(self.clbr_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_pars_left.setFont(font)
        self.pb_pars_left.setObjectName("pb_pars_left")
        self.horizontalLayout_3.addWidget(self.pb_pars_left)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lab_clb1 = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_clb1.setFont(font)
        self.lab_clb1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_clb1.setObjectName("lab_clb1")
        self.horizontalLayout_4.addWidget(self.lab_clb1)
        self.pb_clb1 = QtWidgets.QPushButton(self.clbr_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_clb1.sizePolicy().hasHeightForWidth())
        self.pb_clb1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clb1.setFont(font)
        self.pb_clb1.setObjectName("pb_clb1")
        self.horizontalLayout_4.addWidget(self.pb_clb1)
        self.lab_clb0 = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_clb0.setFont(font)
        self.lab_clb0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_clb0.setObjectName("lab_clb0")
        self.horizontalLayout_4.addWidget(self.lab_clb0)
        self.pb_clb0 = QtWidgets.QPushButton(self.clbr_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_clb0.sizePolicy().hasHeightForWidth())
        self.pb_clb0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clb0.setFont(font)
        self.pb_clb0.setObjectName("pb_clb0")
        self.horizontalLayout_4.addWidget(self.pb_clb0)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lab_clb3 = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_clb3.setFont(font)
        self.lab_clb3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_clb3.setObjectName("lab_clb3")
        self.horizontalLayout_5.addWidget(self.lab_clb3)
        self.pb_clb3 = QtWidgets.QPushButton(self.clbr_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_clb3.sizePolicy().hasHeightForWidth())
        self.pb_clb3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clb3.setFont(font)
        self.pb_clb3.setObjectName("pb_clb3")
        self.horizontalLayout_5.addWidget(self.pb_clb3)
        self.lab_clb2 = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_clb2.setFont(font)
        self.lab_clb2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_clb2.setObjectName("lab_clb2")
        self.horizontalLayout_5.addWidget(self.lab_clb2)
        self.pb_clb2 = QtWidgets.QPushButton(self.clbr_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_clb2.sizePolicy().hasHeightForWidth())
        self.pb_clb2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clb2.setFont(font)
        self.pb_clb2.setObjectName("pb_clb2")
        self.horizontalLayout_5.addWidget(self.pb_clb2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lab_adc_code = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_adc_code.setFont(font)
        self.lab_adc_code.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_adc_code.setObjectName("lab_adc_code")
        self.horizontalLayout_6.addWidget(self.lab_adc_code)
        self.lab_adc_txt = QtWidgets.QLabel(self.clbr_page)
        self.lab_adc_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_adc_txt.setObjectName("lab_adc_txt")
        self.horizontalLayout_6.addWidget(self.lab_adc_txt)
        self.lab_zero = QtWidgets.QLabel(self.clbr_page)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.lab_zero.setFont(font)
        self.lab_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_zero.setObjectName("lab_zero")
        self.horizontalLayout_6.addWidget(self.lab_zero)
        self.pb_zero = QtWidgets.QPushButton(self.clbr_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_zero.sizePolicy().hasHeightForWidth())
        self.pb_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_zero.setFont(font)
        self.pb_zero.setObjectName("pb_zero")
        self.horizontalLayout_6.addWidget(self.pb_zero)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.sw_pages.addWidget(self.clbr_page)
        self.manu_page = QtWidgets.QWidget()
        self.manu_page.setObjectName("manu_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.manu_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hl_4 = QtWidgets.QHBoxLayout()
        self.hl_4.setObjectName("hl_4")
        self.pb_logo_right = QtWidgets.QPushButton(self.manu_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_logo_right.setFont(font)
        self.pb_logo_right.setObjectName("pb_logo_right")
        self.hl_4.addWidget(self.pb_logo_right)
        spacerItem7 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_4.addItem(spacerItem7)
        self.lab_manu = QtWidgets.QLabel(self.manu_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_manu.setFont(font)
        self.lab_manu.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_manu.setObjectName("lab_manu")
        self.hl_4.addWidget(self.lab_manu)
        spacerItem8 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_4.addItem(spacerItem8)
        self.pb_clbr_left = QtWidgets.QPushButton(self.manu_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_clbr_left.setFont(font)
        self.pb_clbr_left.setObjectName("pb_clbr_left")
        self.hl_4.addWidget(self.pb_clbr_left)
        self.gridLayout_2.addLayout(self.hl_4, 0, 0, 1, 1)
        self.hl = QtWidgets.QHBoxLayout()
        self.hl.setObjectName("hl")
        self.rb_inp0 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp0.sizePolicy().hasHeightForWidth())
        self.rb_inp0.setSizePolicy(sizePolicy)
        self.rb_inp0.setObjectName("rb_inp0")
        self.hl.addWidget(self.rb_inp0)
        self.rb_inp1 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp1.sizePolicy().hasHeightForWidth())
        self.rb_inp1.setSizePolicy(sizePolicy)
        self.rb_inp1.setObjectName("rb_inp1")
        self.hl.addWidget(self.rb_inp1)
        self.rb_inp2 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp2.sizePolicy().hasHeightForWidth())
        self.rb_inp2.setSizePolicy(sizePolicy)
        self.rb_inp2.setObjectName("rb_inp2")
        self.hl.addWidget(self.rb_inp2)
        self.rb_inp3 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp3.sizePolicy().hasHeightForWidth())
        self.rb_inp3.setSizePolicy(sizePolicy)
        self.rb_inp3.setObjectName("rb_inp3")
        self.hl.addWidget(self.rb_inp3)
        self.rb_inp4 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp4.sizePolicy().hasHeightForWidth())
        self.rb_inp4.setSizePolicy(sizePolicy)
        self.rb_inp4.setObjectName("rb_inp4")
        self.hl.addWidget(self.rb_inp4)
        self.rb_inp5 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp5.sizePolicy().hasHeightForWidth())
        self.rb_inp5.setSizePolicy(sizePolicy)
        self.rb_inp5.setObjectName("rb_inp5")
        self.hl.addWidget(self.rb_inp5)
        self.rb_inp6 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp6.sizePolicy().hasHeightForWidth())
        self.rb_inp6.setSizePolicy(sizePolicy)
        self.rb_inp6.setObjectName("rb_inp6")
        self.hl.addWidget(self.rb_inp6)
        self.rb_inp7 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_inp7.sizePolicy().hasHeightForWidth())
        self.rb_inp7.setSizePolicy(sizePolicy)
        self.rb_inp7.setObjectName("rb_inp7")
        self.hl.addWidget(self.rb_inp7)
        self.gridLayout_2.addLayout(self.hl, 1, 0, 1, 1)
        self.hl_2 = QtWidgets.QHBoxLayout()
        self.hl_2.setObjectName("hl_2")
        self.rb_out6 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_out6.sizePolicy().hasHeightForWidth())
        self.rb_out6.setSizePolicy(sizePolicy)
        self.rb_out6.setObjectName("rb_out6")
        self.hl_2.addWidget(self.rb_out6)
        self.rb_out7 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_out7.sizePolicy().hasHeightForWidth())
        self.rb_out7.setSizePolicy(sizePolicy)
        self.rb_out7.setObjectName("rb_out7")
        self.hl_2.addWidget(self.rb_out7)
        self.rb_out8 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_out8.sizePolicy().hasHeightForWidth())
        self.rb_out8.setSizePolicy(sizePolicy)
        self.rb_out8.setObjectName("rb_out8")
        self.hl_2.addWidget(self.rb_out8)
        self.rb_out9 = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_out9.sizePolicy().hasHeightForWidth())
        self.rb_out9.setSizePolicy(sizePolicy)
        self.rb_out9.setObjectName("rb_out9")
        self.hl_2.addWidget(self.rb_out9)
        self.rb_outa = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_outa.sizePolicy().hasHeightForWidth())
        self.rb_outa.setSizePolicy(sizePolicy)
        self.rb_outa.setObjectName("rb_outa")
        self.hl_2.addWidget(self.rb_outa)
        self.rb_outb = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_outb.sizePolicy().hasHeightForWidth())
        self.rb_outb.setSizePolicy(sizePolicy)
        self.rb_outb.setObjectName("rb_outb")
        self.hl_2.addWidget(self.rb_outb)
        self.rb_outc = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_outc.sizePolicy().hasHeightForWidth())
        self.rb_outc.setSizePolicy(sizePolicy)
        self.rb_outc.setObjectName("rb_outc")
        self.hl_2.addWidget(self.rb_outc)
        self.rb_outd = QtWidgets.QRadioButton(self.manu_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_outd.sizePolicy().hasHeightForWidth())
        self.rb_outd.setSizePolicy(sizePolicy)
        self.rb_outd.setObjectName("rb_outd")
        self.hl_2.addWidget(self.rb_outd)
        self.gridLayout_2.addLayout(self.hl_2, 2, 0, 1, 1)
        self.sw_pages.addWidget(self.manu_page)
        self.logo_page = QtWidgets.QWidget()
        self.logo_page.setObjectName("logo_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logo_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_3 = QtWidgets.QHBoxLayout()
        self.hl_3.setObjectName("hl_3")
        self.pb_main_right = QtWidgets.QPushButton(self.logo_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_main_right.setFont(font)
        self.pb_main_right.setObjectName("pb_main_right")
        self.hl_3.addWidget(self.pb_main_right)
        spacerItem9 = QtWidgets.QSpacerItem(58, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_3.addItem(spacerItem9)
        self.lab_logo = QtWidgets.QLabel(self.logo_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lab_logo.setFont(font)
        self.lab_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_logo.setObjectName("lab_logo")
        self.hl_3.addWidget(self.lab_logo)
        spacerItem10 = QtWidgets.QSpacerItem(68, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_3.addItem(spacerItem10)
        self.pb_manu_left = QtWidgets.QPushButton(self.logo_page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_manu_left.setFont(font)
        self.pb_manu_left.setObjectName("pb_manu_left")
        self.hl_3.addWidget(self.pb_manu_left)
        self.verticalLayout.addLayout(self.hl_3)
        self.gl = QtWidgets.QGridLayout()
        self.gl.setObjectName("gl")
        self.lab_dva_tkm = QtWidgets.QLabel(self.logo_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_dva_tkm.sizePolicy().hasHeightForWidth())
        self.lab_dva_tkm.setSizePolicy(sizePolicy)
        self.lab_dva_tkm.setObjectName("lab_dva_tkm")
        self.gl.addWidget(self.lab_dva_tkm, 0, 0, 1, 2)
        self.lab_version = QtWidgets.QLabel(self.logo_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_version.sizePolicy().hasHeightForWidth())
        self.lab_version.setSizePolicy(sizePolicy)
        self.lab_version.setObjectName("lab_version")
        self.gl.addWidget(self.lab_version, 1, 1, 1, 1)
        self.rb_master = QtWidgets.QRadioButton(self.logo_page)
        self.rb_master.setObjectName("rb_master")
        self.gl.addWidget(self.rb_master, 1, 0, 1, 1)
        self.lab_cheksum = QtWidgets.QLabel(self.logo_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_cheksum.sizePolicy().hasHeightForWidth())
        self.lab_cheksum.setSizePolicy(sizePolicy)
        self.lab_cheksum.setObjectName("lab_cheksum")
        self.gl.addWidget(self.lab_cheksum, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gl.addItem(spacerItem11, 2, 0, 1, 1)
        self.lab_tokom = QtWidgets.QLabel(self.logo_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_tokom.sizePolicy().hasHeightForWidth())
        self.lab_tokom.setSizePolicy(sizePolicy)
        self.lab_tokom.setObjectName("lab_tokom")
        self.gl.addWidget(self.lab_tokom, 3, 1, 1, 1)
        self.lab_mail = QtWidgets.QLabel(self.logo_page)
        self.lab_mail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_mail.setObjectName("lab_mail")
        self.gl.addWidget(self.lab_mail, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gl)
        self.sw_pages.addWidget(self.logo_page)
        self.gridLayout.addWidget(self.sw_pages, 2, 0, 1, 2)
        self.lab_phase.raise_()
        self.sw_pages.raise_()
        self.lab_weight.raise_()
        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setObjectName("menuBar")
        self.menu_clbr = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_clbr.setFont(font)
        self.menu_clbr.setObjectName("menu_clbr")
        self.menu_rep = QtWidgets.QMenu(self.menu_clbr)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_rep.setFont(font)
        self.menu_rep.setObjectName("menu_rep")
        self.menu_clb = QtWidgets.QMenu(self.menu_clbr)
        self.menu_clb.setObjectName("menu_clb")
        self.menu_conf = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_conf.setFont(font)
        self.menu_conf.setObjectName("menu_conf")
        self.menu_time = QtWidgets.QMenu(self.menu_conf)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_time.setFont(font)
        self.menu_time.setObjectName("menu_time")
        self.menu_weight = QtWidgets.QMenu(self.menu_conf)
        self.menu_weight.setObjectName("menu_weight")
        self.menu_nnn = QtWidgets.QMenu(self.menu_conf)
        self.menu_nnn.setObjectName("menu_nnn")
        self.menu_flags = QtWidgets.QMenu(self.menu_conf)
        self.menu_flags.setObjectName("menu_flags")
        self.menu_oper = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_oper.setFont(font)
        self.menu_oper.setObjectName("menu_oper")
        self.menu_port = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_port.setFont(font)
        self.menu_port.setObjectName("menu_port")
        self.menu_quit = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu_quit.setFont(font)
        self.menu_quit.setObjectName("menu_quit")
        Window.setMenuBar(self.menuBar)
        self.action_pcsn = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_pcsn.setFont(font)
        self.action_pcsn.setObjectName("action_pcsn")
        self.action_round = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_round.setFont(font)
        self.action_round.setObjectName("action_round")
        self.action_rep0 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_rep0.setFont(font)
        self.action_rep0.setObjectName("action_rep0")
        self.action_rep1 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_rep1.setFont(font)
        self.action_rep1.setObjectName("action_rep1")
        self.action_rep2 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_rep2.setFont(font)
        self.action_rep2.setObjectName("action_rep2")
        self.action_rep3 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_rep3.setFont(font)
        self.action_rep3.setObjectName("action_rep3")
        self.action_clb0 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_clb0.setFont(font)
        self.action_clb0.setObjectName("action_clb0")
        self.action_clb1 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_clb1.setFont(font)
        self.action_clb1.setObjectName("action_clb1")
        self.action_clb2 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_clb2.setFont(font)
        self.action_clb2.setObjectName("action_clb2")
        self.action_clb3 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_clb3.setFont(font)
        self.action_clb3.setObjectName("action_clb3")
        self.action_unld = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_unld.setFont(font)
        self.action_unld.setObjectName("action_unld")
        self.action_pre_feed = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_pre_feed.setFont(font)
        self.action_pre_feed.setObjectName("action_pre_feed")
        self.action_pre_meas = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_pre_meas.setFont(font)
        self.action_pre_meas.setObjectName("action_pre_meas")
        self.action_btm_chk = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_btm_chk.setFont(font)
        self.action_btm_chk.setObjectName("action_btm_chk")
        self.action_shrt_tmo = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_shrt_tmo.setFont(font)
        self.action_shrt_tmo.setObjectName("action_shrt_tmo")
        self.action_long_tmo = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_long_tmo.setFont(font)
        self.action_long_tmo.setObjectName("action_long_tmo")
        self.action_sleep = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_sleep.setFont(font)
        self.action_sleep.setObjectName("action_sleep")
        self.action_ready = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_ready.setFont(font)
        self.action_ready.setObjectName("action_ready")
        self.action_cycle = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_cycle.setFont(font)
        self.action_cycle.setObjectName("action_cycle")
        self.action_t_s_min = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_t_s_min.setFont(font)
        self.action_t_s_min.setObjectName("action_t_s_min")
        self.action_doza = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_doza.setFont(font)
        self.action_doza.setObjectName("action_doza")
        self.action_upr1 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_upr1.setFont(font)
        self.action_upr1.setObjectName("action_upr1")
        self.action_upr2 = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_upr2.setFont(font)
        self.action_upr2.setObjectName("action_upr2")
        self.action_dozz = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_dozz.setFont(font)
        self.action_dozz.setObjectName("action_dozz")
        self.action_tarz = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_tarz.setFont(font)
        self.action_tarz.setObjectName("action_tarz")
        self.action_debounce = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_debounce.setFont(font)
        self.action_debounce.setObjectName("action_debounce")
        self.action_tare_skip = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_tare_skip.setFont(font)
        self.action_tare_skip.setObjectName("action_tare_skip")
        self.action_auto_cycle = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_auto_cycle.setFont(font)
        self.action_auto_cycle.setObjectName("action_auto_cycle")
        self.action_auto_start = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_auto_start.setFont(font)
        self.action_auto_start.setObjectName("action_auto_start")
        self.action_filter_fs = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.action_filter_fs.setFont(font)
        self.action_filter_fs.setObjectName("action_filter_fs")
        self.actionAdapt = QtWidgets.QAction(Window)
        font = QtGui.QFont()
        self.actionAdapt.setFont(font)
        self.actionAdapt.setObjectName("actionAdapt")
        self.action_master = QtWidgets.QAction(Window)
        self.action_master.setObjectName("action_master")
        self.action_about = QtWidgets.QAction(Window)
        self.action_about.setObjectName("action_about")
        self.action_exit = QtWidgets.QAction(Window)
        self.action_exit.setObjectName("action_exit")
        self.action_fast = QtWidgets.QAction(Window)
        self.action_fast.setObjectName("action_fast")
        self.menu_rep.addAction(self.action_rep0)
        self.menu_rep.addAction(self.action_rep1)
        self.menu_rep.addAction(self.action_rep2)
        self.menu_rep.addAction(self.action_rep3)
        self.menu_clb.addAction(self.action_clb0)
        self.menu_clb.addAction(self.action_clb1)
        self.menu_clb.addAction(self.action_clb2)
        self.menu_clb.addAction(self.action_clb3)
        self.menu_clbr.addAction(self.menu_rep.menuAction())
        self.menu_clbr.addAction(self.menu_clb.menuAction())
        self.menu_clbr.addAction(self.action_pcsn)
        self.menu_clbr.addAction(self.action_round)
        self.menu_clbr.addAction(self.action_master)
        self.menu_time.addAction(self.action_unld)
        self.menu_time.addAction(self.action_pre_feed)
        self.menu_time.addAction(self.action_pre_meas)
        self.menu_time.addAction(self.action_btm_chk)
        self.menu_time.addAction(self.action_shrt_tmo)
        self.menu_time.addAction(self.action_long_tmo)
        self.menu_time.addAction(self.action_sleep)
        self.menu_time.addAction(self.action_ready)
        self.menu_time.addAction(self.action_cycle)
        self.menu_time.addAction(self.action_t_s_min)
        self.menu_weight.addAction(self.action_doza)
        self.menu_weight.addAction(self.action_upr1)
        self.menu_weight.addAction(self.action_upr2)
        self.menu_weight.addAction(self.action_dozz)
        self.menu_weight.addAction(self.action_tarz)
        self.menu_nnn.addAction(self.action_debounce)
        self.menu_nnn.addAction(self.action_tare_skip)
        self.menu_nnn.addAction(self.action_filter_fs)
        self.menu_nnn.addAction(self.actionAdapt)
        self.menu_flags.addAction(self.action_auto_cycle)
        self.menu_flags.addAction(self.action_auto_start)
        self.menu_conf.addAction(self.menu_time.menuAction())
        self.menu_conf.addAction(self.menu_weight.menuAction())
        self.menu_conf.addAction(self.menu_nnn.menuAction())
        self.menu_conf.addAction(self.menu_flags.menuAction())
        self.menu_oper.addAction(self.action_fast)
        self.menu_quit.addAction(self.action_about)
        self.menu_quit.addAction(self.action_exit)
        self.menuBar.addAction(self.menu_clbr.menuAction())
        self.menuBar.addAction(self.menu_conf.menuAction())
        self.menuBar.addAction(self.menu_oper.menuAction())
        self.menuBar.addAction(self.menu_port.menuAction())
        self.menuBar.addAction(self.menu_quit.menuAction())

        self.retranslateUi(Window)
        self.sw_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "MainWindow"))
        self.lab_phase.setText(_translate("Window", "00 : STOP_phase-bla-bla"))
        self.lab_weight.setText(_translate("Window", "-50.00kg"))
        self.lab_lev.setText(_translate("Window", "LEV"))
        self.rb_tare.setToolTip(_translate("Window", "Fix tare"))
        self.rb_tare.setText(_translate("Window", "TAR"))
        self.lab_stab.setText(_translate("Window", "STB"))
        self.pb_pars_right.setText(_translate("Window", "PARS"))
        self.lab_main.setText(_translate("Window", "MAIN"))
        self.pb_logo_left.setText(_translate("Window", "LOGO"))
        self.lab_dose.setText(_translate("Window", "50.00kg"))
        self.pb_dose_nom.setText(_translate("Window", "Dose Nominal"))
        self.lab_total.setText(_translate("Window", "Total 1234567.89kg"))
        self.pb_unload.setText(_translate("Window", "UNLOAD"))
        self.pb_stop.setText(_translate("Window", "STOP"))
        self.pb_run.setText(_translate("Window", "RUN "))
        self.pb_clbr_right.setText(_translate("Window", "CLBR"))
        self.lab_pars.setText(_translate("Window", "PARAMS"))
        self.pb_main_left.setText(_translate("Window", "MAIN"))
        self.lab_parameter.setText(_translate("Window", "   -999999999 "))
        self.lab_parname.setText(_translate("Window", "22: Name of Par"))
        self.pb_next.setText(_translate("Window", "NEXT"))
        self.pb_prev.setText(_translate("Window", "PREV"))
        self.pb_parv.setText(_translate("Window", "PAR V"))
        self.pb_parn.setText(_translate("Window", "PAR N"))
        self.pb_manu_right.setText(_translate("Window", "MANU"))
        self.lab_clbr.setText(_translate("Window", "CLBR"))
        self.pb_pars_left.setText(_translate("Window", "PARS"))
        self.lab_clb1.setText(_translate("Window", "123456.789"))
        self.pb_clb1.setText(_translate("Window", "CLBR1"))
        self.lab_clb0.setText(_translate("Window", "123456.789"))
        self.pb_clb0.setText(_translate("Window", "CLBR0"))
        self.lab_clb3.setText(_translate("Window", "123456.789"))
        self.pb_clb3.setText(_translate("Window", "CLBR3"))
        self.lab_clb2.setText(_translate("Window", "123456.789"))
        self.pb_clb2.setText(_translate("Window", "CLBR2"))
        self.lab_adc_code.setText(_translate("Window", "123456.789"))
        self.lab_adc_txt.setText(_translate("Window", "ADC"))
        self.lab_zero.setText(_translate("Window", "-1234.56kg"))
        self.pb_zero.setText(_translate("Window", "ZERO"))
        self.pb_logo_right.setText(_translate("Window", "LOGO"))
        self.lab_manu.setText(_translate("Window", "MANUAL"))
        self.pb_clbr_left.setText(_translate("Window", "CLBR"))
        self.rb_inp0.setText(_translate("Window", "i&0"))
        self.rb_inp1.setText(_translate("Window", "i&1"))
        self.rb_inp2.setText(_translate("Window", "i&2"))
        self.rb_inp3.setText(_translate("Window", "i&3"))
        self.rb_inp4.setText(_translate("Window", "i&4"))
        self.rb_inp5.setText(_translate("Window", "i&5"))
        self.rb_inp6.setText(_translate("Window", "i&6"))
        self.rb_inp7.setText(_translate("Window", "i&7"))
        self.rb_out6.setText(_translate("Window", "o6"))
        self.rb_out7.setText(_translate("Window", "o7"))
        self.rb_out8.setText(_translate("Window", "o&8"))
        self.rb_out9.setText(_translate("Window", "o&9"))
        self.rb_outa.setText(_translate("Window", "oA"))
        self.rb_outb.setText(_translate("Window", "oB"))
        self.rb_outc.setText(_translate("Window", "oC"))
        self.rb_outd.setText(_translate("Window", "o&D"))
        self.pb_main_right.setText(_translate("Window", "MAIN"))
        self.lab_logo.setText(_translate("Window", "LOGO"))
        self.pb_manu_left.setText(_translate("Window", "MANU"))
        self.lab_dva_tkm.setText(_translate("Window", "DVA TKM16 Batch Weigher Controler"))
        self.lab_version.setText(_translate("Window", "Program version 32"))
        self.rb_master.setText(_translate("Window", "Master Bit"))
        self.lab_cheksum.setText(_translate("Window", "Check sum 0xABCD"))
        self.lab_tokom.setText(_translate("Window", "TOKOM, Kyiv-2018"))
        self.lab_mail.setText(_translate("Window", "tokom2009@gmail.com"))
        self.menu_clbr.setTitle(_translate("Window", "&CLBR"))
        self.menu_rep.setTitle(_translate("Window", "&Rep"))
        self.menu_clb.setTitle(_translate("Window", "&Clb"))
        self.menu_conf.setTitle(_translate("Window", "CO&NF"))
        self.menu_time.setTitle(_translate("Window", "&TIME"))
        self.menu_weight.setTitle(_translate("Window", "&WEIGHT"))
        self.menu_nnn.setTitle(_translate("Window", "&NNN"))
        self.menu_flags.setTitle(_translate("Window", "&FLAGS"))
        self.menu_oper.setTitle(_translate("Window", "OPER"))
        self.menu_port.setTitle(_translate("Window", "PO&RT"))
        self.menu_quit.setTitle(_translate("Window", "&Quit"))
        self.action_pcsn.setText(_translate("Window", "&PcsN"))
        self.action_round.setText(_translate("Window", "R&ound"))
        self.action_rep0.setText(_translate("Window", "&0"))
        self.action_rep1.setText(_translate("Window", "&1"))
        self.action_rep2.setText(_translate("Window", "&2"))
        self.action_rep3.setText(_translate("Window", "&3"))
        self.action_clb0.setText(_translate("Window", "&0"))
        self.action_clb1.setText(_translate("Window", "&1"))
        self.action_clb2.setText(_translate("Window", "&2"))
        self.action_clb3.setText(_translate("Window", "&3"))
        self.action_unld.setText(_translate("Window", "&Unld"))
        self.action_pre_feed.setText(_translate("Window", "&PreFeed"))
        self.action_pre_meas.setText(_translate("Window", "pr&eMeas"))
        self.action_btm_chk.setText(_translate("Window", "&BtmChk"))
        self.action_shrt_tmo.setText(_translate("Window", "&ShrtTMO"))
        self.action_long_tmo.setText(_translate("Window", "&LongTMO"))
        self.action_sleep.setText(_translate("Window", "Sleep"))
        self.action_ready.setText(_translate("Window", "&Ready"))
        self.action_cycle.setText(_translate("Window", "&Cycle"))
        self.action_t_s_min.setText(_translate("Window", "&TSmin"))
        self.action_doza.setText(_translate("Window", "&Doza"))
        self.action_upr1.setText(_translate("Window", "&Upr1"))
        self.action_upr2.setText(_translate("Window", "U&pr2"))
        self.action_dozz.setText(_translate("Window", "D&ozZ"))
        self.action_tarz.setText(_translate("Window", "&TarZ"))
        self.action_debounce.setText(_translate("Window", "&Debounce"))
        self.action_tare_skip.setText(_translate("Window", "&TareSkip"))
        self.action_auto_cycle.setText(_translate("Window", "&AutoCycle"))
        self.action_auto_start.setText(_translate("Window", "A&utoStart"))
        self.action_filter_fs.setText(_translate("Window", "&FilterNN"))
        self.actionAdapt.setText(_translate("Window", "&Adapt"))
        self.action_master.setText(_translate("Window", "&Master Bit"))
        self.action_about.setText(_translate("Window", "&About"))
        self.action_exit.setText(_translate("Window", "&Exit"))
        self.action_fast.setText(_translate("Window", "&FAST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

